### ISSUE TITLE
Importing problems

### ISSUE THREAD

**Issue by Typhonragewind** [julianpoy/RecipeSage-selfhost#1]
Hello!

Thanks again for providing us with a way for selfhosting, it is extremely appreciated!

I did find a issue importing from Paprika files (log below). You  have, of course, no obligation whatsoever to fix this, but if you're ever bored and want to take a look, it would be awesome!

`
GET /users/friends?token=c2740d403df31b117dc87a38f46c38fce530d691e0cce701ec0e195c37fa26dd9963e6b65fff9ac8eed8b47fdf1ec1d6 200 178.418 ms - 58

GET /users/capabilities?token=c2740d403df31b117dc87a38f46c38fce530d691e0cce701ec0e195c37fa26dd9963e6b65fff9ac8eed8b47fdf1ec1d6 304 11.846 ms - -

/tmp/paprika-import/5eb2826877beff3896828c96e5ede048

(node:1) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

logged

POST /import/paprika?token=c2740d403df31b117dc87a38f46c38fce530d691e0cce701ec0e195c37fa26dd9963e6b65fff9ac8eed8b47fdf1ec1d6 500 1448.362 ms - 216

GET /labels/?token=c2740d403df31b117dc87a38f46c38fce530d691e0cce701ec0e195c37fa26dd9963e6b65fff9ac8eed8b47fdf1ec1d6 304 39.882 ms - -`

**Comment by julianpoy** [comment]
Hey there! Thanks for reporting the issue - missed this, I'll have to keep closer :eyes: on this repo.

I've added it to the ToDo for the upcoming release.

**Comment by Typhonragewind** [comment]
> Hey there! Thanks for reporting the issue - missed this, I'll have to keep closer 👀 on this repo.
> 
> I've added it to the ToDo for the upcoming release.

I really appreciate that what you're doing for us selfhosters :)

And on the risk of sounding annoying, the importing from paprika is still not working for me, but i can't get an error in any log this time, this is weird. (clean install, not updating)

**Comment by julianpoy** [comment]
This should be fixed in the latest beta version (v2.7.3-beta1), and included with the next full release.

**Comment by Typhonragewind** [comment]
> 
> 
> This should be fixed in the latest beta version (v2.7.3-beta1), and included with the next full release.

Ahh, my bad, i thought it had already been included in the 1.1 release
