### ISSUE TITLE
Question: Installing RecipeSage on Raspberry Pi

### ISSUE THREAD

**Issue by abhilesh** [julianpoy/RecipeSage-selfhost#11]
I'm trying to install RecipeSage on a Raspberry Pi 4 and the primary issue I run into while install is that there is no matching manifest for linux/arm/v7 for minio. Could you please point me to a minio image that would work for raspberry pi, I tried a few without any success.

I have an AWS S3 account, so can I completely bypass the minio parts of the installation?

Thanks a lot for your work!

**Comment by julianpoy** [comment]
Hi @abhilesh! I was on vacation last week so just getting to GitHub notifications now.

You can completely remove everything related to minio, as well as remove/update anything marked as minio-related (see comments in the docker-compose file).

I'm not sure about a minio build for ARM, but the project is really intended to run on S3 anyway.
