### ISSUE TITLE
Installing on Ubuntu

### ISSUE THREAD

**Issue by myopenflixr** [julianpoy/RecipeSage-selfhost#13]
Hello,

I am attempting to install this on an Ubuntu VM I created with my Proxmox cluster at my house.

I've installed Docker & Docker Compose and have removed everything in docker-compose.yaml file relating to minio. Everything seems to install fine, but there appears to be an issue with ingredient-instruction-classifier. The container is in a constant "restarting mode".

When I look at the logs, here is what I am seeing:

> ingredient-instruction-classifier_1  | Illegal instruction (core dumped)
> recipe-sage_ingredient-instruction-classifier_1 exited with code 132
> ingredient-instruction-classifier_1  | Illegal instruction (core dumped)
> recipe-sage_ingredient-instruction-classifier_1 exited with code 132

Any suggestions on how to fix this?

Also, I cannot save recipes or add images and not sure what the issue is. Looking at logs, I'm getting a 415 Unsupported Media Type when trying to upload any images. And i've tried uploading jpg and png images with the same error.

Thank You,
Mike

**Comment by julianpoy** [comment]
Sounds like your CPU doesn't support AVX extensions required for Tensorflow. Further debugging would really have to be done on the Tensorflow side and unfortunately isn't related to RecipeSage. That said, the app can run without the classifier, it just won't be as accurate when auto-importing.

Image route returning 415 can be a number of things, but is almost certainly an issue with your S3 credentials since you've removed minio. Are there any associated logs?

**Comment by myopenflixr** [comment]
I am trying to run this on a home server, not an AWS S3 server. Is this possible to run on a home server and bypass AWS completely? If so, are there any additional changes that need to be made to the docker-compose file on my end?

If you're in need of any of my log files, please let me know what you need and where I can find them.

**Comment by julianpoy** [comment]
> I've installed Docker & Docker Compose and have removed everything in docker-compose.yaml file relating to minio

> I am trying to run this on a home server, not an AWS S3 server

These two things would be contradictory. Either you're using S3 in which case you want to remove all minio references, or you're not using S3 and therefore need minio. By the sound of what you've described in your latest reply, I suggest leaving the docker-compose.yaml from this repository as-is.

The logs you posted above are unrelated to minio/S3. They are related to the machine learning container not supporting your processor instruction set. This is a Tensorflow thing, not related to RecipeSage.

**Comment by myopenflixr** [comment]
Hi,

Running Fresh installation of Ubuntu 20.04 on Proxmox as a Virtual Machine.

Nothing to do with AWS or S3. Not running anything on Amazon Web Servers. Looking for solution to run this on home server.

Leaving docker-compose "as-is" produces many errors as it seems as if it relies on AWS S3 services.

Please advise.

Thanks,

Mike

**Comment by julianpoy** [comment]
Mind posting those errors?
