### ISSUE TITLE
ARM64 Images

### ISSUE THREAD

**Issue by f1ana** [julianpoy/RecipeSage-selfhost#15]
Hello!  I've been a user of RecipeSage for a few months now, and really enjoying it.  I was hoping to be able to run the self hosted solution on a Raspberry Pi, but it looks like all images are amd64 only.  Is it possible to add ARM64 support as well?  Or is something within the solution x86 specific?  Thank you!

**Comment by julianpoy** [comment]
Nothing specific to x86 AFAIK. I'd be happy to take a look at building for ARM.

**Comment by deltatux** [comment]
> Nothing specific to x86 AFAIK. I'd be happy to take a look at building for ARM.

+1 on an ARM version, it appears that there are some Docker images that it relies on like pushpin does not have an ARM version.

**Comment by julianpoy** [comment]
Yeah pushpin will be a blocker on this one. If anyone wants to open a PR with a builder for ARM I'll be happy to approve. Gave it a go with buildx but it's quite the undertaking.

**Comment by MitchellSingleton** [comment]
Does this container meet the need of arm64? https://hub.docker.com/r/zimbres/pushpin

**Comment by julianpoy** [comment]
@MitchellSingleton seems like it could, though it doesn't have any documentation so am a _little_ skeptical. Wouldn't be opposed to putting a note regarding that image as an option.

Unfortunately that's not the only issue. I've had trouble getting buildx not to time out (from taking so long) in CircleCI. If anyone has advice on getting buildx going with good performance (or another option), I'd love some assistance.

**Comment by julianpoy** [comment]
All of the selfhost infra now supports ARM except for pushpin. Users can swap to the `zimbres/pushpin` image for ARM usage, though I have not validated that image as genuine and trusted.

I looked into building a pushpin image but ran into some issues. For now, I'm considering this issue closed. Please comment if you have any issues.
