### ISSUE TITLE
A few issues on Synology DSM

### ISSUE THREAD

**Issue by justinlaselva** [julianpoy/RecipeSage-selfhost#16]
Howdy, Julian!

I am attempting to set up RecipeSage-selfhost on my Synology RS820+ running DSM 6.2.4-25556 Update 2.

I am using the api-latest and static-latest Docker images from the Registry. I have not made any modifications to the `docker-compose.yml` or `proxy.conf` files except to change the `ports` to `51433:80`, since 80/tcp is in use on my system.

I can get docker-compose to run and complete successfully, but two of the containers it creates immediately go into a restart loop:

- **julianpoy/ingredient-instruction-classifier:latest** restarts endlessly; based on your feedback in other threads, this container uses TensorFlow and depends on the AVX instruction set, and I can confirm that my RS820's Atom processor does not support it. So, no big deal, I can kill that container.

- **postgres** also restarts endlessly; the logs show the following repeatedly:

```
PostgreSQL Database directory appears to contain a database; Skipping initialization

2021-10-21 05:01:49.375 UTC [1] FATAL:  database files are incompatible with server
2021-10-21 05:01:49.375 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 13, which is not compatible with this version 14.0 (Debian 14.0-1.pgdg110+1).
```

If I edit the `docker-compose.yml` file to specify `postgres:13` for the postgres Docker image, I can then get docker-compose to complete successfully with stable containers, minus the AVX-required one.

After that, I can see that 51433/tcp is open, and I can connect to it, but all I can get out of nginx is a 504 (time-out). I need to do more digging there before I ask for your help… just wanted to report the Postgres problem as a potential bug.

Thanks for making RecipeSage open source! I really appreciate your helping out the community.

Justin

**Comment by julianpoy** [comment]
Glad it's sorted.
