### ISSUE TITLE
Different results between official and selfhosted version when importing recipes from URL

### ISSUE THREAD

**Issue by Waseh** [julianpoy/RecipeSage-selfhost#17]
Hi Julian

Firstly thanks for a great service!

I've just deployed the selfhosted version of RecipeSage after playing about with the official hosted version for a couple of days.
All in all it went very smooth, however i'm seeing different results when importing recipes between the two versions.

One recipe, which imports without any hickups in the official version, doesn't populate any fields but the source URL in the selfhosted version. [Example (in danish)](https://mandekogebogen.dk/italiensk-ragu.725.html)

Even recipes that do import in the selfhosted version are processed way better in the official version (requiring less cleanup)
[Example (in danish)](https://www.valdemarsro.dk/fajitas/)

I tried poking around the docker container logs with no, to me, clear culprit.

I'm really digging RecipeSage, the import tool is very powerful, just a shame it's not performing as well on the selfhosted edition for me.

**Comment by julianpoy** [comment]
Hi there!

The two should be exactly the same. Are you sure that there are no logs coming from the ingredient instruction classifier container and that it's running?

**Comment by Waseh** [comment]
Hi Julian

I clearly missed the logs from the ingredient instruction classifier container as the culprit is most certainly here.
Seems Tensorflow isn't running due to some instruction set incompatibility. Apparently my VPS doesn't support the AVX instruction set. [I think this is where my problem arises from](https://github.com/tensorflow/tensorflow/issues/19584)
I'm not sure if there's an easy solution for that. Might ask my VPS provider for input.

**Comment by julianpoy** [comment]
Yeah that's unfortunately just a limitation of tensorflow.

**Comment by Waseh** [comment]
Well thanks to the lovely modularity I'm now hosting the ingredient-instruction-classifier on my home server that does support AVX, while the other containers are running on my VPS.
Somehow though I'm still not getting consistently similar imports from URLs when comparing the officially hosted version compared to my own.

Some recipes (even ones that completely failed when the ingredient-instruction-classifier wasn't running) now import way better while others are still garbled.

The recipes that import with the best results trigger a "POST / 200" line in the  ingredient-instruction-classifier logs while the ones that import poorly don't. 
It seems to depend on the website as imports from one specific website always triggers a POST line while another specific site never does. 
However neither of the results actually match the results produced by the officially hosted version.

Maybe it's just not meant to be 😂

I would try and host the whole stack on my home server, but it's running unraid which makes using docker-compose very tedius.

I think i might just roll with the official hosted version 😉

**Comment by justinlaselva** [comment]
Hey @Waseh, if it's not too much trouble, could you elaborate on how you got the ingredient-instruction-classifier working on a separate host than the rest of your Docker installation? I'm running mine on a Synology NAS which also lacks support for the AVX instruction set, so that container won't run. I haven't had any problems with RecipeSage once I got it set up (although the grocery list sorting is obviously a little off without that container running), for what it's worth.
