### ISSUE TITLE
Trouble deploying on Qnap NAS

### ISSUE THREAD

**Issue by cheezgr8r** [julianpoy/RecipeSage-selfhost#18]
I have been trying to deploy on a Qnap NAS for several days and I don't know what to look at next.  I use portainer to deploy and maintain containers with no problems accessing other containers, so I don't think it's a firewall or interconnectivity problem.

Because this deployment is on a NAS I had to change the port from 80. I did this on docker-compose.yml line 8 to '- 18011:80' and in proxy.conf line 5 to 'listen 18011;'
I also had to declare the absolute path to the proxy.conf file on line 6. Aside from credentials I've made no other changes.

After deploying with all the containers up and running (except for create minio buckets), and running /app/migrate on the API, when I try to access recipe-sage I get 'ERR_CONNECTION_REFUSED' but no access attempt in the nginx container logs. 

I've tried removing all the containers, images, and networks and redeploying but still the same behavior. I've also tried pulling up a local browser on the NAS and accessing from localhost:18011 with the same results.

I have other containers on this NAS, but this is my first experience with nginx, so I don't know if there's other changes I need to make to proxy.conf to get the proxy manager to look at the NAS ip address.

I can post logs or files if that'll help, just not sure where to look next

**Comment by cheezgr8r** [comment]
Looking at logs again I see a lot of 'listening on ipv6 by default' which might explain some of this. In there a way to force it to ipv4? Or is that unrelated?

**Comment by cheezgr8r** [comment]
Figured out that I should not have touched the proxy.conf file. Just got it up and running!

**Comment by julianpoy** [comment]
👍🏼
