### ISSUE TITLE
People Page / Sharing between family members

### ISSUE THREAD

**Issue by lekr74** [julianpoy/RecipeSage-selfhost#2]
Hello,
First of all, thanks a lot for this amazing work !
As some others, I prefer a lot to self host the services that I use, so I don't use your public version. I use version 2.7.2 beta 3 with a self host S3 on another VM
I would love to have the same possibility to have the People Page and to be able to share all the recipes between family members.
Is there something I can activate to have it ?

Thanks in advance !

**Comment by julianpoy** [comment]
Yep, you can share all of your recipes with your family by using the "public profile" feature.

https://recipesage.com/#/tips-tricks-tutorials/people-profile

**Comment by lekr74** [comment]
Hello,

Thanks for your answer, but I don't see a People tab as there is on the public version. Where could i find it ?


![image](https://user-images.githubusercontent.com/61479019/110765002-ff2d7e00-8253-11eb-8284-cac671237086.png)

**Comment by julianpoy** [comment]
Apologies, I forgot that the initial selfhost release doesn't yet have the public profile feature enabled.

I'm working on getting it setup for compatibility with the selfhosted version. I should be able to push a beta release that enables it tomorrow.

**Comment by lekr74** [comment]
yeah, super great ! Don't apologize, you're doing a very great work ! Take all the time you need and I'll be happy to use it when it'll be ready !
Thanks !!

**Comment by lekr74** [comment]
Hello,
Any chance you had the time for this ?

Thanks

**Comment by julianpoy** [comment]
I hadn't - been quite busy (plus, got my second COVID vaccine!). Was just able to update it and push in `v2.7.3-beta4`
