### ISSUE TITLE
Meals move but display doesn't update; two feature requests

### ISSUE THREAD

**Issue by justinlaselva** [julianpoy/RecipeSage-selfhost#20]
I've been running RecipeSage self-hosted for about three months now and it's amazing. Thank you!

I have one bug report and two feature requests. Obviously, this is a project offered in good will, so I'm not expecting you to implement them, but if you ever decide to expand the feature set in the future, these would be cool:

- Preferences persisting across sessions. Right now, when I log out or open RecipeSage in a new browser, using the same account, I have to set all the preferences from scratch each time. For example, changing the meal planner to start on Sundays rather than Mondays, turning off the display of descriptions on the My Recipes page, turning on the sidebar navigation, etc.
- Implement CalDAV support for the Meal Plans calendar so that meals can be synchronized to a CalDAV client.

For the bug report: Sometimes, maybe about 20% of the time, when I click and drag an existing meal on the calendar to a new date, the display does not update and the meal stays where it is. However, if I refresh the page, the meal will be on the date to which I moved it. I am using Firefox 96.0.3 on macOS.

Please let me know if you need any further details. Thanks again!

**Comment by julianpoy** [comment]
Hey there! Mind filing these each as separate issues under the application repository? This repo is for the selfhost docker configs.

https://github.com/julianpoy/recipesage

**Comment by justinlaselva** [comment]
Of course, moving them now. Thanks.
