### ISSUE TITLE
Different results between official and selfhosted version when importing recipes from URL

### ISSUE THREAD

**Issue by kjanezic95** [julianpoy/RecipeSage-selfhost#21]
Hello,

first sorry to open a thread with the same name. I have some trouble importing recipes.. The problem is the same as in this thread:
https://github.com/julianpoy/RecipeSage-selfhost/issues/17

On official site the import works fine, but not on selfhosted one. If I can provide more info I will do it ASAP.

This is the "docker ps -a":

<pre>docker@xxxx:~/docker/RecipeSage-selfhost$ docker ps -a
CONTAINER ID   IMAGE                                                 COMMAND                  CREATED             STATUS                            PORTS                                   NAMES
e0e5602fdf02   nginx                                                 "/docker-entrypoint.…"   31 minutes ago      Up 31 minutes                     0.0.0.0:9926->80/tcp, :::9926->80/tcp   recipesage-selfhost_proxy_1
3e3b906e4fd6   julianpoy/recipesage-selfhost:api-latest              "docker-entrypoint.s…"   31 minutes ago      Up 31 minutes                     80/tcp                                  recipesage-selfhost_api_1
8d6cff73fa76   minio/mc                                              "sh -c ' /usr/bin/mc…"   31 minutes ago      Exited (0) 12 minutes ago                                                 recipesage-selfhost_create-minio-buckets_1
b9dce1f4e164   postgres                                              "docker-entrypoint.s…"   31 minutes ago      Up 31 minutes                     5432/tcp                                recipesage-selfhost_postgres_1
9bf8338a0e5d   browserless/chrome:1.28.0-chrome-stable               "./start.sh"             31 minutes ago      Up 31 minutes                     3000/tcp                                recipesage-selfhost_browserless_1
7c4a6dcf52ed   docker.elastic.co/elasticsearch/elasticsearch:7.6.1   "/usr/local/bin/dock…"   31 minutes ago      Up 31 minutes                     9200/tcp, 9300/tcp                      recipesage-selfhost_elasticsearch_1
41587ed69607   fanout/pushpin:1.27.0                                 "docker-entrypoint.s…"   31 minutes ago      Up 31 minutes                     5560-5563/tcp, 7999/tcp                 recipesage-selfhost_pushpin_1
d3209470c9ab   julianpoy/ingredient-instruction-classifier:latest    "docker-entrypoint.s…"   31 minutes ago      Restarting (132) 55 seconds ago                                           recipesage-selfhost_ingredient-instruction-classifier_1
41a4e11274d5   minio/minio                                           "/usr/bin/docker-ent…"   31 minutes ago      Up 31 minutes                     9000/tcp                                recipesage-selfhost_minio_1
86d1e125dc2a   julianpoy/recipesage-selfhost:static-latest           "/docker-entrypoint.…"   31 minutes ago      Up 31 minutes                     80/tcp                                  recipesage-selfhost_static_1</pre>

And logs from julianpoy/ingredient-instruction-classifier:latest:

<pre>docker@xxxx:~/docker/RecipeSage-selfhost$ docker logs d3209470c9ab
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)</pre>

Also logs from minio/mc:

<pre>docker@xxxx:~/docker/RecipeSage-selfhost$ docker logs 8d6cff73fa76
Added `myminio` successfully.
Bucket created successfully `myminio/recipesage-selfhost`.
Access permission for `myminio/recipesage-selfhost` is set to `public`
Added `myminio` successfully.
mc: <ERROR> Unable to make bucket `myminio/recipesage-selfhost`. Your previous request to create the named bucket succeeded and you already own it.
Access permission for `myminio/recipesage-selfhost` is set to `public`
Added `myminio` successfully.
mc: <ERROR> Unable to make bucket `myminio/recipesage-selfhost`. Your previous request to create the named bucket succeeded and you already own it.
Access permission for `myminio/recipesage-selfhost` is set to `public`
Added `myminio` successfully.
mc: <ERROR> Unable to make bucket `myminio/recipesage-selfhost`. Your previous request to create the named bucket succeeded and you already own it.
Access permission for `myminio/recipesage-selfhost` is set to `public`</pre>

Sadly this is as far as I know to go. I have not changed anything, I downloaded git selfhosted folder and started up the docker.

I would be very thankful for solution as I really like this product :)

**Comment by julianpoy** [comment]
The logs from the ingredient-instruction-classifier indicate that it's crashing. That would explain the difference in results between your local scrape vs the hosted copy.

That error is coming from Tensorflow, but it's likely your processor doesn't support AVX instructions which are required for Tensorflow support.
