### ISSUE TITLE
Self-host error on login ~ error on command docker-compose exec api /app/migrate

### ISSUE THREAD

**Issue by teunbruijnen** [julianpoy/RecipeSage-selfhost#22]
Hello,

I  successfully self-hosted RecipeSage a while back and wanted to get back into it. After `docker-compose pull` I am receiving an error when trying to log in:

![image](https://user-images.githubusercontent.com/22060261/156626308-130cbe76-307f-426a-9587-1faec277f60f.png)
I realized I had not ran migrations, however when I try the command `docker-compose exec api /app/migrate` I get either of these two errors (the IP in the 2nd error varies) :
![image](https://user-images.githubusercontent.com/22060261/156626254-66d9a0c7-bd8c-4f1e-a2be-f2f1263f01d8.png)

**Comment by teunbruijnen** [comment]
Looks like the 'ingredient-instruction-classifier:latest and 'postgres' are having issues:
![image](https://user-images.githubusercontent.com/22060261/156627435-0432bd01-597e-4b53-83aa-3f6e15c4b1d7.png)

**Comment by julianpoy** [comment]
The postgres container is crashing according to your second comment, which would explain why the database migrations won't run.

Mind posting the logs from the postgres container?

**Comment by teunbruijnen** [comment]
Hi @julianpoy thanks for your fast reply. Here's the log from the postgres container, quite clear:
![image](https://user-images.githubusercontent.com/22060261/157505801-62e04624-a86c-491c-97f9-0ac329e1feb0.png)

Any way to modify the database files so they are compatible?

**Comment by julianpoy** [comment]
Missed the notification for your comment here, sorry!

You can just specify an older Postgres image tag to line up with your existing database files. Sounds like you might have pulled a newer version of Postgres that's not compatible with your existing data.

**Comment by julianpoy** [comment]
That's related to this here:

https://github.com/julianpoy/RecipeSage-selfhost/issues/14#issuecomment-932643093

**Comment by teunbruijnen** [comment]
Aha, clear. Too bad that my CPU does not support AVX. Thanks a lot for your replies and the good work on RecipeSage! Have a great day
