### ISSUE TITLE
docker-compose exec api /app/migrate error, also minio won't stay running

### ISSUE THREAD

**Issue by bonelifer** [julianpoy/RecipeSage-selfhost#24]
```
❯ sudo docker-compose exec api /app/migrate
(node:35) UnhandledPromiseRejectionWarning: SequelizeHostNotFoundError: getaddrinfo ENOTFOUND postgres
    at /snapshot/app/Backend/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:173:24
    at Connection.connectingErrorHandler (/snapshot/app/Backend/node_modules/pg/lib/client.js:194:14)
    at Connection.emit (events.js:315:20)
    at Socket.reportStreamError (/snapshot/app/Backend/node_modules/pg/lib/connection.js:71:10)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:35) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:35) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
Also minio won't stay running:
```
Added `myminio` successfully.
Bucket created successfully `myminio/recipesage-selfhost`.
Access permission for `myminio/recipesage-selfhost` is set to `public`
Added `myminio` successfully.
mc: <ERROR> Unable to make bucket `myminio/recipesage-selfhost`. Your previous request to create the named bucket succeeded and you already own it.
Access permission for `myminio/recipesage-selfhost` is set to `public`
Added `myminio` successfully.
mc: <ERROR> Unable to make bucket `myminio/recipesage-selfhost`. Your previous request to create the named bucket succeeded and you already own it.
Access permission for `myminio/recipesage-selfhost` is set to `public`
```

**Comment by bonelifer** [comment]
So I'm not able to register. Otherwise all the other containers are up.

**Comment by bonelifer** [comment]
I looked around at the postgres and noticed it said I was out of disk space on /dev/sda2.  I forgotten about having timeshift installed. I'm in the process of reinstalling RecipeSage, now that I have 66GiB instead of 0 bytes. Will leave this open until I have it installed again and the previous errors are gone.

**Comment by bonelifer** [comment]
Seems to be working now.  Meh...  Two questions. First there is a `minio/mc` image which is stopped is this supposed to be like this?  Second being that this is multi-user setup, is there an admin panel?

**Comment by julianpoy** [comment]
Hey there! Didn't see a notification for this.

> First there is a minio/mc image which is stopped is this supposed to be like this? 
Yep, that initializes your minio bucket.

> Second being that this is multi-user setup, is there an admin panel?
Nope, it's all registration based. Pretty much just a self hostable copy of what exists at recipesage.com since people had asked to be able to selfhost it.

**Comment by bonelifer** [comment]
Thanks for getting back to me.  Since posting this I've looked  at RecipeSage, Tandoor Recipes and Grocy + Recipe Buddy.

 Grocy lost out because RB isn't ready yet and I don't want to manually enter recipes from online. That and I don't like it's everything in the kitchen sink setup. I'm not here to keep track of batteries and other stuff. Just recipes.  RecipeSage lost because I feel it has just too many moving parts and just feels heavy not from a performance perspective, but from an overall perspective.  I really hope you continued success. Thanks again for getting back to me.

**Comment by julianpoy** [comment]
Absolutely. Use what fits you best.
