### ISSUE TITLE
Importing and Migrating self-hosted instance issues

### ISSUE THREAD

**Issue by cheezgr8r** [julianpoy/RecipeSage-selfhost#26]
I'm migrating recipe-sage to a new server, and I'm at the point to populate the new instance with all the recipes from the old instance. I had tried exporting to json-LD and importing, but I get a warning that the file doesn't end in json and `an unexpected error ocurred` when I try to import anyway. Both are running in Portainer. Is there a different method I can use to migrate?

**Comment by julianpoy** [comment]
Mind uploading your export file? (feel free to shorten it if you don't want to expose your recipes)

**Comment by cheezgr8r** [comment]
Yeah, it's just recipes. Nothing sensitive

[recipesage-data-1660916523914.json-ld.zip](https://github.com/julianpoy/RecipeSage-selfhost/files/9382639/recipesage-data-1660916523914.json-ld.zip)

**Comment by cheezgr8r** [comment]
Do you have an exported file that I could try uploading? I just tried extract a few different recipes from the exported file and none of them imported. Also, which container in the stack should I monitor for logs while attempting to import?

**Comment by julianpoy** [comment]
My goodness, I'm sorry I haven't had 👀 on this repo/issue.

I see the issue - it's due to the fact that the image URLs generated by the JSON-LD export in the selfhosted version aren't truly "valid" (they're relative).

The logs to watch would be those from the `api` container.

**Comment by julianpoy** [comment]
So looking deeper into the issue here - it really comes down to the fact that I have no idea what your externally facing URL would be to point as the "source" for the image, since JSON-LD format requires specifying public-facing URLs for the images array rather than some base64-encoded image.

For your specific question, I'd recommend just copying your 3 docker volumes to your new machine.

https://rakhesh.com/linux-bsd/copying-a-docker-volume-from-one-host-to-another/

**Comment by cheezgr8r** [comment]
Thank you for digging into this! I know some images I uploaded manually. Could that have caused the relative url's? I'm not in a rush to migrate, so I may wait and test out your fix

**Comment by julianpoy** [comment]
Hi @cheezgr8r, totally forgot to take a look into this. Let me see if I can put a PR up tonight.

**Comment by julianpoy** [comment]
I think I'm going to have to close this by recommending that you copy your minio data to the other system. The JSON-LD export will have to stay incompatible with selfhosted images on minio for now, unfortunately. I'm opening an issue in the main repository for this, however.

**Comment by julianpoy** [comment]
https://github.com/julianpoy/RecipeSage/issues/796
