### ISSUE TITLE
Cannot start service proxy error

### ISSUE THREAD

**Issue by HawaiianPizza** [julianpoy/RecipeSage-selfhost#27]
`ERROR: for proxy  Cannot start service proxy: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/ubuntu/docker/recipesage/proxy.conf" to rootfs at "/etc/nginx/conf.d/default.conf": mount /home/ubuntu/docker/recipesage/proxy.conf:/etc/nginx/conf.d/default.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`

Hello everyone! I'm trying to get RecipeSage to run on my Raspberry Pi 4 (using Ubuntu 20.04) but docker-compose produces the error abovce. I tried running it on my laptop (Ubuntu 22.04) and the same error persists. I'll be more than happy to provide any additional info if needed.

**Comment by julianpoy** [comment]
So Raspberry Pi wouldn't be supported because ARM isn't supported at the moment (see #15).

Can you post some logs from your laptop?

**Comment by HawaiianPizza** [comment]
> Can you post some logs from your laptop?

Here's what I get when I run `docker-compose logs`: https://pastebin.com/0chHU7ES

**Comment by julianpoy** [comment]
So sorry! I don't check this repo often (usually check the RecipeSage one), on me!

From those logs it looks like everything is running correctly. Are you just not able to hit the application on the public facing port?
