### ISSUE TITLE
Photos do not appear

### ISSUE THREAD

**Issue by milesian01** [julianpoy/RecipeSage-selfhost#29]
First time user here. I'm up and running on a Windows host in WSL mode with the provided docker-compose file verbatim (except for host port number) but none of the photos are showing, including recipes and profile photos.  For your review, below are some log entries recorded by Docker when I tried adding a photo to my user profile, which ultimately results in showing the standard "broken" image in the browser.

<details><summary>docker log entries</summary>
recipesage-proxy-1 | 2022/10/03 03:33:25 [warn] 33#33: *184 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000002, client: 172.19.0.1, server: localhost, request: "POST /api/images/?token=1deb137e2a85b0d811ef9ec9feb47589de14ca74ea9c6322a7f10a8ecb320058dcf72163daeab7ef748dd5481b018581 HTTP/1.1", host: "localhost:8900", referrer: "http://localhost:8900/"

recipesage-api-1 | POST /images/?token=1deb137e2a85b0d811ef9ec9feb47589de14ca74ea9c6322a7f10a8ecb320058dcf72163daeab7ef748dd5481b018581 200 55.547 ms - 474

recipesage-proxy-1 | 172.19.0.1 - - [03/Oct/2022:03:33:25 +0000] "POST /api/images/?token=1deb137e2a85b0d811ef9ec9feb47589de14ca74ea9c6322a7f10a8ecb320058dcf72163daeab7ef748dd5481b018581 HTTP/1.1" 200 474 "http://localhost:8900/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" "-"

recipesage-proxy-1 | 172.19.0.1 - - [03/Oct/2022:03:33:25 +0000] "GET /minio/recipesage-selfhost/1664768005749 HTTP/1.1" 403 327 "http://localhost:8900/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" "-"
</details>

When I point my browser at the broken image, namely http://localhost:8900/minio/recipesage-selfhost/1664767774266, I get the below:

<details><summary>browser error</summary>
Error

Code: AccessDenied
Message: Access Denied.
Key: 1664767774266
BucketName: recipesage-selfhost
Resource: /recipesage-selfhost/1664767774266
RequestId: 171A7179FDF7E33C
HostId: 0d53d13a-4f5e-4bbf-a1b9-31de194f73fd
</details>

Looking in the "miniodata" volume, I see the "/recipesage-selfhost/1664767774266" bucket folder. The only file in there is a 9 KB xl.meta file with no sign of the photo I uploaded.

Please advise on what may be wrong with my setup, thanks much.

**Comment by thezanderlv** [comment]
Im having the same problem on a line server its 403 errors all uploaded photos.

**Comment by julianpoy** [comment]
The newest update should fix this issue.
