### ISSUE TITLE
Bonus Features on Self Hosted version

### ISSUE THREAD

**Issue by lekr74** [julianpoy/RecipeSage-selfhost#3]
Hello again,

Is there any way to activate the Bonus Features on the self hosted version ?

Thanks in advance

**Comment by julianpoy** [comment]
Not currently - I was planning on writing a script that'll insert those entries into the DB, but haven't gotten around to it.

Shouldn't be too hard if you'd like to do it yourself - you'll have to add an entry to the subscriptions table.

**Comment by lekr74** [comment]
Thanks !
Could you precise what I should insert in the database please ?
I tried to do it, but didn't manage to succeed.

**Comment by julianpoy** [comment]
Hi @lekr74,

I'll get back to you on this. I'll see if I can put together a script for this tomorrow rather than trying to document how to do this manually.

**Comment by julianpoy** [comment]
Created a script for this: `/app/activate`. Have to head to bed and it's not done building, so I'll have to give it a go after work tomorrow. After that will update the readme.

**Comment by julianpoy** [comment]
Documented in the readme!
