### ISSUE TITLE
MinIO, PostgreSQL, and Elasticsearch errors after upgrading to v1.20

### ISSUE THREAD

**Issue by justinlaselva** [julianpoy/RecipeSage-selfhost#33]
Howdy!

I ran into some problems upgrading from RecipeSage 2.8.1 to 2.9.0 (included in the 1.20 release of this self-hosted repo)… basically, everything blew up. I pulled down the new `docker-compose.yml` file and ran it; everything built successfully, but there seems to be a problem with using the latest versions of MinIO, PostgreSQL, and Elasticsearch. After the containers were built, RecipeSage's static pages would load, but I couldn't log in. The MinIO and PostgreSQL containers kept bouncing, and the Elasticsearch container was using something like 80% CPU and north of 9 GB of RAM on launch before it, too, started bouncing. (This is on a Synology NAS device with an Intel Atom processor and 18 GB of RAM.)

The MinIO container was reporting:

```
ERROR Unable to use the drive /data: Drive /data: found backend type fs, expected xl or xl-single
```

The PostgreSQL container was reporting:

```
The data directory was initialized by PostgreSQL version 13, which is not compatible with this version 15.1 (Debian 15.1-1.pgdg110+1). FATAL:  database files are incompatible with server
```

The Elasticsearch container was reporting:

```
fatal exception while booting Elasticsearch
cannot upgrade a node from version [7.6.1] directly to version [8.4.3], upgrade to version [7.17.0] first.
```

It looks like MinIO has discontinued their filesystem mode as of February 2022, so some kind of local conversion process to [Single-Node Single-Drive mode](https://min.io/docs/minio/linux/operations/install-deploy-manage/migrate-fs-gateway.html) might be necessary for those running MinIO, as I am.

Admittedly, aside from the functional deprecation in MinIO, it's probable that these issues wouldn't have cropped up if I had been rebuilding my RecipeSage container regularly and keeping up with the latest dependencies but, alas, it had been up for quite a while and so jumping straight to the latest versions of PostgreSQL and Elasticsearch was no bueno.

I was able to blow away my RecipeSage data mounts, restore from backups, and change the `docker-compose.yml` file to use older versions of MinIO (`minio/minio:RELEASE.2022-10-24T18-35-07Z`) and PostgreSQL (`postgres:14.6`) and this has solved the problem; I am back on RecipeSage 2.8.1 and things appear to be working as expected, again. For those who don't want to wrangle with MinIO, staying at `RELEASE.2022-10-24T18-35-07Z` appears to be the only solution.

Just thought I'd let you know about the MinIO problem! As always, thanks for the great program.

**Comment by julianpoy** [comment]
Hey there! Sorry about that. I would like to get some automated testing up for this selfhosted setup. I spend most of my time focused on the hosted version but should really put a bit more love into this version.

As of now I've pinned the minio version to the version you listed here.

WRT PostgreSQL - I recommend sticking with the same version of PostgreSQL as the one you setup with for now. PostgreSQL migration between version is possible, but not worth the headache.

You should be able to upgrade to newer versions of RecipeSage with just an upgrade to ElasticSearch. ElasticSearch is annoying - I would blow away the ElasticSearch data locally, update to the version recommended in the docker-compose, and then hit the "reset search index" button in your account settings.
