### ISSUE TITLE
Search returns odd results

### ISSUE THREAD

**Issue by iwilliamson** [julianpoy/RecipeSage-selfhost#38]
I've tried this on my self hosted site and on the "official" site.

If you create an account, and import the attached recipes, then search for "pork", you get "Cheese Cocktail Crisps" and "Pink lemonade cake", along with some pork recipes.  Happens with lots of other searched too...returns lots of results that don't contain the word.

Any thoughts on why?

[Recipes to Import](https://www.squids.ca/__files/recipes.json)

**Comment by julianpoy** [comment]
From what you describe I believe the search is behaving correctly. Pork is two letters off from pink. ElasticSearch includes misspellings as part of a proper "fuzzy" search. You should always see results with an exact match returned first, however.

This behavior is the same as things like Google - there's just a lot more on the first few pages, hah.

I _could_ make this behavior customizable for the self hosted instance via an environment variable (https://github.com/julianpoy/RecipeSage/blob/master/Backend/src/services/elastic.js#L145), but that would in turn mean that fuzzy searching (misspellings) are no longer covered.

**Comment by iwilliamson** [comment]
Ha!  Indeed.  The "Cheese Cocktail Crisps" has "fork" in the directions.

I understand your dilemma.  Would it be possible to, like Google search, put the word in quotes for an exact match or something like that?

**Comment by julianpoy** [comment]
Missed your reply, apologies. Definitely possible, I'll put an issue in the main repo for this.

**Comment by iwilliamson** [comment]
Thanks!
