### ISSUE TITLE
App connection to Self Hosted Site?  Is it possible?

### ISSUE THREAD

**Issue by iwilliamson** [julianpoy/RecipeSage-selfhost#39]
I'm running a self hosted copy of RecipeSage, and wanted the Android app to be able to connect to it (as opposed to the "official" site.  Is that possible?

**Comment by julianpoy** [comment]
No way to do that at the moment.

The Android app is just the website wrapped inside of a TWA. It offers no additional functionality over the website or installing as PWA. In other words, if you selfhost RecipeSage behind HTTPS and "add to homescreen", you'll have the same functionality as the Android app.

**Comment by iwilliamson** [comment]
Fair enough.  Thanks!
