### ISSUE TITLE
Unable to upload image

### ISSUE THREAD

**Issue by illegalPointer** [julianpoy/RecipeSage-selfhost#40]
When trying to upload an image for a recipe the process fails. At the same time something related with not finding a bucket pop-up on docker logs, so it is probably related.

Also I'm not sure if it is supposed to grab an image when trying to autofill from URL. That would be great, although I guess somewhat complicated.

**Comment by julianpoy** [comment]
Would you be able to post those logs by chance?

**Comment by illegalPointer** [comment]
Sure thing mate

proxy_1                              | 2023/03/17 08:27:37 [warn] 30#30: *99 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000002, client: X.X.X.X, server: localhost, request: "POST /api/images?token=815dace64969c832bee8555721d7421b61341d0f2e191926a967f41837d08bb92bb88506c0aae172d4452a09038c11f1& HTTP/1.1", host: "mydomain.com:60000", referrer: "http://mydomain.com:60000/"
api_1                                | Sharp Error: NoSuchBucket: The specified bucket does not exist
proxy_1                              | X.X.X.X - - [17/Mar/2023:08:27:39 +0000] "POST /api/images?token=815dace64969c832bee8555721d7421b61341d0f2e191926a967f41837d08bb92bb88506c0aae172d4452a09038c11f1& HTTP/1.1" 415 2203 "http://mydomain.com:60000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" "-"
api_1                                | POST /images?token=815dace64969c832bee8555721d7421b61341d0f2e191926a967f41837d08bb92bb88506c0aae172d4452a09038c11f1& 415 2029.329 ms - 2203
api_1                                | NoSuchBucket: The specified bucket does not exist
api_1                                |     at Request.extractError (/snapshot/app/Backend/node_modules/s3fs/node_modules/aws-sdk/lib/services/s3.js:538:35)
api_1                                |     at Request.callListeners (/snapshot/app/Backend/node_modules/s3fs/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
api_1                                |     at Request.emit (/snapshot/app/Backend/node_modules/s3fs/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
api_1                                |     at Request.emit (/snapshot/app/Backend/node_modules/s3fs/node_modules/aws-sdk/lib/request.js:668:14)
api_1                                |     at Request.transition (/snapshot/app/Backend/node_modules/s3fs/node_modules/aws-sdk/lib/request.js:22:10)
api_1                                |     at AcceptorStateMachine.runTo (/snapshot/app/Backend/node_modules/s3fs/node_modules/aws-sdk/lib/state_machine.js:14:12)
api_1                                |     at /snapshot/app/Backend/node_modules/s3fs/node_modules/aws-sdk/lib/state_machine.js:26:10
api_1                                |     at Request.<anonymous> (/snapshot/app/Backend/node_modules/s3fs/node_modules/aws-sdk/lib/request.js:38:9)
api_1                                |     at Request.<anonymous> (/snapshot/app/Backend/node_modules/s3fs/node_modules/aws-sdk/lib/request.js:670:12)
api_1                                |     at Request.callListeners (/snapshot/app/Backend/node_modules/s3fs/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
api_1                                |     at Request.emit (/snapshot/app/Backend/node_modules/s3fs/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
api_1                                |     at Request.emit (/snapshot/app/Backend/node_modules/s3fs/node_modules/aws-sdk/lib/request.js:668:14)
api_1                                |     at Request.transition (/snapshot/app/Backend/node_modules/s3fs/node_modules/aws-sdk/lib/request.js:22:10)
api_1                                |     at AcceptorStateMachine.runTo (/snapshot/app/Backend/node_modules/s3fs/node_modules/aws-sdk/lib/state_machine.js:14:12)
api_1                                |     at /snapshot/app/Backend/node_modules/s3fs/node_modules/aws-sdk/lib/state_machine.js:26:10
api_1                                |     at Request.<anonymous> (/snapshot/app/Backend/node_modules/s3fs/node_modules/aws-sdk/lib/request.js:38:9)

**Comment by julianpoy** [comment]
Didn't see this until today, apologies. That indicates that the minio bucket for the minio container wasn't created.

This here is responsible for creating the minio bucket, so I suspect this didn't get run: https://github.com/julianpoy/RecipeSage-selfhost/blob/main/docker-compose.yml#L109-L120

As an aside, I'm replacing minio completely here: https://github.com/julianpoy/RecipeSage/pull/999

**Comment by julianpoy** [comment]
Updates to use local filesystem have been merged. No more minio!
