### ISSUE TITLE
ingredient-instruction-classifier failing with core dumped error

### ISSUE THREAD

**Issue by emacsified** [julianpoy/RecipeSage-selfhost#41]
Hi! 

I'm running this with a basically-stock configuration copied from your `docker-compose` example here.
The site runs okay, however the `ingredient-instruction-classifier` image is in a restart loop with the following error:

`ingredient-instruction-classifier_1  | Illegal instruction (core dumped)`

**Comment by julianpoy** [comment]
Your processor probably doesn't support AVX instructions which is required for the machine learning segment of the classifier. Everything should work fine still, just with reduced accuracy for the automatic clip tool function on websites with no/reduced formatting.

See https://github.com/julianpoy/RecipeSage-selfhost/issues/14#issuecomment-932643093
