### ISSUE TITLE
Unable to sign in to my account after setting up local host

### ISSUE THREAD

**Issue by gavakas** [julianpoy/RecipeSage-selfhost#45]
Hi, 

I have self hosted recipesage with docker but every time i try to enter my credentials I get this error "An unexpected error occurred. Please try again. If the problem continues to occur, please contact me."

Can you please help me? 

Thank you.

**Comment by julianpoy** [comment]
Hey there - I will need the logs from your docker containers at the time when you encounter the error. The error you mention is generic and just indicates something unexpected is happening, so I can't really identify the problem in your setup that way.

**Comment by gavakas** [comment]
Hey Julian, 

Thank you for your help. I think that the file i have attached, is the one you asked for. I copy and pasted the logs from docker to a text file. :/ Does it work? 


Best regards, 
Papaevagelou Giannis

**Comment by gavakas** [comment]
[recipesage-selfhost logs.docx](https://github.com/julianpoy/RecipeSage-selfhost/files/11380450/recipesage-selfhost.logs.docx)

**Comment by gavakas** [comment]
Good morning Julian!

Yes absolutely. Will do during the day and will send here.

Best regards,

Giannis Papaevagelou

**Comment by gavakas** [comment]
Here you go: 



Thank you Julian!

Best regards, 
Papaevagelou Giannis

**Comment by julianpoy** [comment]
Hi @gavakas The attachment there didn't come through. It might be better to post it via the web interface rather than via email. If that's not possible, you can send it directly to me at julian@recipesage.com.

**Comment by gavakas** [comment]
Hi Julian, 

Sorry for not responding earlier, last days were crazy.
Here are the logs from the whole stack. still can't log in with my credentials. 

Thank you for your help. 
[recipeSage logs.docx](https://github.com/julianpoy/RecipeSage-selfhost/files/11445886/recipeSage.logs.docx)

**Comment by julianpoy** [comment]
Looks like it's elasticsearch crashing.

From your logs:
```
elasticsearch_1                      | ERROR: Elasticsearch exited unexpectedly
```

Can you post just the logs from `docker-compose logs elasticsearch`? There might be a lot since it's been restarting so much, so probably best to `docker-compose down; docker-compose up -d` to get a fresh set from the start, since the start is what we really care about.

**Comment by gavakas** [comment]
Hi Julian, 

I cleraed them out and run docker-compose logs elasticsearch twice. This is what i got. 

macmini:RecipeSage-selfhost gavakas$ docker-compose logs elasticsearch
Attaching to recipesage-selfhost_elasticsearch_1
elasticsearch_1                      | Created elasticsearch keystore in /usr/share/elasticsearch/config/elasticsearch.keystore
macmini:RecipeSage-selfhost gavakas$ docker-compose logs elasticsearch
Attaching to recipesage-selfhost_elasticsearch_1
elasticsearch_1                      | Created elasticsearch keystore in /usr/share/elasticsearch/config/elasticsearch.keystore
elasticsearch_1                      | 
elasticsearch_1                      | ERROR: Elasticsearch exited unexpectedly
elasticsearch_1                      | 
elasticsearch_1                      | ERROR: Elasticsearch exited unexpectedly
macmini:RecipeSage-selfhost gavakas$ 


Any ideas?

**Comment by julianpoy** [comment]
How much RAM does the PC that you're running this on have?

**Comment by gavakas** [comment]
It's a Mac mini 2014 with 8gb ram

Best regards,

Giannis Papaevagelou

**Comment by julianpoy** [comment]
Can you run `free -m` with the stack running and post the result?

**Comment by gavakas** [comment]
Just rum free -m but got this in return -bash: free: command not found

**Comment by gavakas** [comment]
Hi, 

Any progress on finding a solution? Thank you Julian.

**Comment by julianpoy** [comment]
Hi @gavakas - I don't have anymore debugging steps for you at this point. It's something to do with your setup (likely available RAM related), which is causing ElasticSearch to die, but beyond that there just isn't enough information.

I'd recommend asking the ElasticSearch community for help debugging. ElasticSearch is a dependency of RecipeSage, but unaffiliated.

**Comment by julianpoy** [comment]
Hi @cesardv - that's a different issue than the one mentioned in the original post. The original post is experiencing crashes while spinning up ElasticSearch. Please open a new issue for the issue you're experiencing, though the logs you posted are for the ingredient instruction classifier which won't prevent startup of the application.

**Comment by julianpoy** [comment]
@gavakas Mind trying the latest from this repository?

**Comment by gavakas** [comment]
HI @julianpoy . Did a fresh install of docker to a new 16gb macmini but still get the same result 'An unexpected error occurred. Please try again. If the problem continues to occur, please contact me' .

**Comment by julianpoy** [comment]
Any new logs? Or is it the same elasticsearch container crashing over and over again?

**Comment by julianpoy** [comment]
And just to confirm, you've run the migration script after setting up the containers, correct?

**Comment by gavakas** [comment]
Just reinstalled docker and redownloaded the code. :( No migration script. I used git clone to download the code and then docker-compose up -d . Should I use the migration script now or should I delete the resipesage-selfhost folder and rerun everything form the begging?

**Comment by julianpoy** [comment]
The setup section outlines the steps in order:

https://github.com/julianpoy/RecipeSage-selfhost#setup

**Comment by gavakas** [comment]
deleted everything and doing it from scratch. ./migrate.sh does way longer than 1 minute. How do i know that it hasn't stuck? How long should i wait and how do i stop it if needed? Its running for 5 minutes now.

**Comment by julianpoy** [comment]
Please send the logs from the api container now that migrations have been run.

**Comment by gavakas** [comment]
Here are the logs from the api1 container:

Error while initializing firebase for notifications

/app/node_modules/@elastic/transport/lib/Transport.js:528

                            : new errors_1.ConnectionError(error.message, result);

                              ^



ConnectionError: connect ECONNREFUSED 172.18.0.3:9200

    at SniffingTransport.request (/app/node_modules/@elastic/transport/lib/Transport.js:528:31)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at Client.PingApi (/app/node_modules/@elastic/elasticsearch/lib/api/api/ping.js:37:12)

    at init (/app/packages/backend/src/services/search/elasticsearch.ts:17:3) {

  meta: {

    body: undefined,

    statusCode: 0,

    headers: {},

    meta: {

      context: null,

      request: {

        params: {

          method: 'HEAD',

          path: '/',

          querystring: '',

          headers: {

            'user-agent': 'elastic-transport-js/8.3.1 (linux 5.10.47-linuxkit-x64; Node.js v18.16.0)',

            'x-elastic-client-meta': 'es=8.4.0,js=18.16.0,t=8.3.1,hc=18.16.0',

            accept: 'application/vnd.elasticsearch+json; compatible-with=8,text/plain'

          }

        },

        options: {},

        id: 1

      },

      name: 'elasticsearch-js',

      connection: Connection {

        url: <ref *1> URL {

          [Symbol(context)]: URLContext {

            href: 'http://elastic:recipesage_selfhost@elasticsearch:9200/',

            origin: 'http://elasticsearch:9200',

            protocol: 'http:',

            hostname: 'elasticsearch',

            pathname: '/',

            search: '',

            username: 'elastic',

            password: 'recipesage_selfhost',

            port: '9200',

            hash: ''

          },

          [Symbol(query)]: URLSearchParams {

            [Symbol(query)]: [],

            [Symbol(context)]: [Circular *1]

          }

        },

        tls: null,

        id: 'http://elasticsearch:9200/',

        timeout: 30000,

        headers: { authorization: 'Basic ZWxhc3RpYzpyZWNpcGVzYWdlX3NlbGZob3N0' },

        deadCount: 0,

        resurrectTimeout: 0,

        _openRequests: 0,

        weight: 1000,

        pool: <ref *2> Pool {

          _events: [Object: null prototype] {},

          _eventsCount: 0,

          _maxListeners: undefined,

          [Symbol(kCapture)]: false,

          [Symbol(destroyed)]: false,

          [Symbol(onDestroyed)]: [],

          [Symbol(closed)]: false,

          [Symbol(onClosed)]: [],

          [Symbol(queue)]: FixedQueue {

            tail: [FixedCircularBuffer],

            head: [FixedCircularBuffer]

          },

          [Symbol(clients)]: [ [Client], [Client] ],

          [Symbol(queued)]: 0,

          [Symbol(onDrain)]: [Function: onDrain],

          [Symbol(onConnect)]: [Function (anonymous)],

          [Symbol(onDisconnect)]: [Function (anonymous)],

          [Symbol(onConnectionError)]: [Function (anonymous)],

          [Symbol(stats)]: PoolStats { [Symbol(pool)]: [Circular *2] },

          [Symbol(dispatch interceptors)]: [],

          [Symbol(connections)]: 256,

          [Symbol(url)]: URL {

            [Symbol(context)]: [URLContext],

            [Symbol(query)]: [URLSearchParams]

          },

          [Symbol(options)]: {

            keepAliveTimeout: 600000,

            keepAliveMaxTimeout: 600000,

            keepAliveTimeoutThreshold: 1000,

            pipelining: 1,

            maxHeaderSize: 16384,

            headersTimeout: 30000,

            bodyTimeout: 30000,

            connect: [Function: connect],

            interceptors: undefined

          },

          [Symbol(factory)]: [Function: defaultFactory],

          [Symbol(Intercepted Dispatch)]: [Function: [dispatch]],

          [Symbol(needDrain)]: false

        },

        [Symbol(status)]: 'alive',

        [Symbol(ca fingerprint)]: null,

        [Symbol(diagnostics)]: Diagnostic {

          _events: [Object: null prototype] {},

          _eventsCount: 0,

          _maxListeners: undefined,

          [Symbol(kCapture)]: false

        },

        [Symbol(event emitter)]: EventEmitter {

          _events: [Object: null prototype] {},

          _eventsCount: 0,

          _maxListeners: undefined,

          [Symbol(kCapture)]: false

        }

      },

      attempts: 3,

      aborted: false

    },

    warnings: [Getter]

  }

}


Node.js v18.16.0

npm notice 

npm notice New minor version of npm available! 9.5.1 -> 9.7.1

npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.7.1>

npm notice Run `npm install -g npm@9.7.1` to update!

npm notice 

Error while initializing firebase for notifications

/app/node_modules/@elastic/transport/lib/Transport.js:528

                            : new errors_1.ConnectionError(error.message, result);

                              ^



ConnectionError: connect ECONNREFUSED 172.18.0.3:9200

    at SniffingTransport.request (/app/node_modules/@elastic/transport/lib/Transport.js:528:31)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at Client.PingApi (/app/node_modules/@elastic/elasticsearch/lib/api/api/ping.js:37:12)

    at init (/app/packages/backend/src/services/search/elasticsearch.ts:17:3) {

  meta: {

    body: undefined,

    statusCode: 0,

    headers: {},

    meta: {

      context: null,

      request: {

        params: {

          method: 'HEAD',

          path: '/',

          querystring: '',

          headers: {

            'user-agent': 'elastic-transport-js/8.3.1 (linux 5.10.47-linuxkit-x64; Node.js v18.16.0)',

            'x-elastic-client-meta': 'es=8.4.0,js=18.16.0,t=8.3.1,hc=18.16.0',

            accept: 'application/vnd.elasticsearch+json; compatible-with=8,text/plain'

          }

        },

        options: {},

        id: 1

      },

      name: 'elasticsearch-js',

      connection: Connection {

        url: <ref *1> URL {

          [Symbol(context)]: URLContext {

            href: 'http://elastic:recipesage_selfhost@elasticsearch:9200/',

            origin: 'http://elasticsearch:9200',

            protocol: 'http:',

            hostname: 'elasticsearch',

            pathname: '/',

            search: '',

            username: 'elastic',

            password: 'recipesage_selfhost',

            port: '9200',

            hash: ''

          },

          [Symbol(query)]: URLSearchParams {

            [Symbol(query)]: [],

            [Symbol(context)]: [Circular *1]

          }

        },

        tls: null,

        id: 'http://elasticsearch:9200/',

        timeout: 30000,

        headers: { authorization: 'Basic ZWxhc3RpYzpyZWNpcGVzYWdlX3NlbGZob3N0' },

        deadCount: 0,

        resurrectTimeout: 0,

        _openRequests: 0,

        weight: 1000,

        pool: <ref *2> Pool {

          _events: [Object: null prototype] {},

          _eventsCount: 0,

          _maxListeners: undefined,

          [Symbol(kCapture)]: false,

          [Symbol(destroyed)]: false,

          [Symbol(onDestroyed)]: [],

          [Symbol(closed)]: false,

          [Symbol(onClosed)]: [],

          [Symbol(queue)]: FixedQueue {

            tail: [FixedCircularBuffer],

            head: [FixedCircularBuffer]

          },

          [Symbol(clients)]: [ [Client], [Client] ],

          [Symbol(queued)]: 0,

          [Symbol(onDrain)]: [Function: onDrain],

          [Symbol(onConnect)]: [Function (anonymous)],

          [Symbol(onDisconnect)]: [Function (anonymous)],

          [Symbol(onConnectionError)]: [Function (anonymous)],

          [Symbol(stats)]: PoolStats { [Symbol(pool)]: [Circular *2] },

          [Symbol(dispatch interceptors)]: [],

          [Symbol(connections)]: 256,

          [Symbol(url)]: URL {

            [Symbol(context)]: [URLContext],

            [Symbol(query)]: [URLSearchParams]

          },

          [Symbol(options)]: {

            keepAliveTimeout: 600000,

            keepAliveMaxTimeout: 600000,

            keepAliveTimeoutThreshold: 1000,

            pipelining: 1,

            maxHeaderSize: 16384,

            headersTimeout: 30000,

            bodyTimeout: 30000,

            connect: [Function: connect],

            interceptors: undefined

          },

          [Symbol(factory)]: [Function: defaultFactory],

          [Symbol(Intercepted Dispatch)]: [Function: [dispatch]],

          [Symbol(needDrain)]: false

        },

        [Symbol(status)]: 'alive',

        [Symbol(ca fingerprint)]: null,

        [Symbol(diagnostics)]: Diagnostic {

          _events: [Object: null prototype] {},

          _eventsCount: 0,

          _maxListeners: undefined,

          [Symbol(kCapture)]: false

        },

        [Symbol(event emitter)]: EventEmitter {

          _events: [Object: null prototype] {},

          _eventsCount: 0,

          _maxListeners: undefined,

          [Symbol(kCapture)]: false

        }

      },

      attempts: 3,

      aborted: false

    },

    warnings: [Getter]

  }

}


Node.js v18.16.0

Error while initializing firebase for notifications

/app/node_modules/@elastic/transport/lib/Transport.js:528

                            : new errors_1.ConnectionError(error.message, result);

                              ^



ConnectionError: connect ECONNREFUSED 172.18.0.3:9200

    at SniffingTransport.request (/app/node_modules/@elastic/transport/lib/Transport.js:528:31)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at Client.PingApi (/app/node_modules/@elastic/elasticsearch/lib/api/api/ping.js:37:12)

    at init (/app/packages/backend/src/services/search/elasticsearch.ts:17:3) {

  meta: {

    body: undefined,

    statusCode: 0,

    headers: {},

    meta: {

      context: null,

      request: {

        params: {

          method: 'HEAD',

          path: '/',

          querystring: '',

          headers: {

Database connection established

            'user-agent': 'elastic-transport-js/8.3.1 (linux 5.10.47-linuxkit-x64; Node.js v18.16.0)',

            'x-elastic-client-meta': 'es=8.4.0,js=18.16.0,t=8.3.1,hc=18.16.0',

            accept: 'application/vnd.elasticsearch+json; compatible-with=8,text/plain'

          }

        },

        options: {},

        id: 1

      },

      name: 'elasticsearch-js',

      connection: Connection {

        url: <ref *1> URL {

          [Symbol(context)]: URLContext {

            href: 'http://elastic:recipesage_selfhost@elasticsearch:9200/',

            origin: 'http://elasticsearch:9200',

            protocol: 'http:',

            hostname: 'elasticsearch',

            pathname: '/',

            search: '',

            username: 'elastic',

            password: 'recipesage_selfhost',

            port: '9200',

            hash: ''

          },

          [Symbol(query)]: URLSearchParams {

            [Symbol(query)]: [],

            [Symbol(context)]: [Circular *1]

          }

        },

        tls: null,

        id: 'http://elasticsearch:9200/',

        timeout: 30000,

        headers: { authorization: 'Basic ZWxhc3RpYzpyZWNpcGVzYWdlX3NlbGZob3N0' },

        deadCount: 0,

        resurrectTimeout: 0,

        _openRequests: 0,

        weight: 1000,

        pool: <ref *2> Pool {

          _events: [Object: null prototype] {},

          _eventsCount: 0,

          _maxListeners: undefined,

          [Symbol(kCapture)]: false,

          [Symbol(destroyed)]: false,

          [Symbol(onDestroyed)]: [],

          [Symbol(closed)]: false,

          [Symbol(onClosed)]: [],

          [Symbol(queue)]: FixedQueue {

            tail: [FixedCircularBuffer],

            head: [FixedCircularBuffer]

          },

          [Symbol(clients)]: [ [Client], [Client] ],

          [Symbol(queued)]: 0,

          [Symbol(onDrain)]: [Function: onDrain],

          [Symbol(onConnect)]: [Function (anonymous)],

          [Symbol(onDisconnect)]: [Function (anonymous)],

          [Symbol(onConnectionError)]: [Function (anonymous)],

          [Symbol(stats)]: PoolStats { [Symbol(pool)]: [Circular *2] },

          [Symbol(dispatch interceptors)]: [],

          [Symbol(connections)]: 256,

          [Symbol(url)]: URL {

            [Symbol(context)]: [URLContext],

            [Symbol(query)]: [URLSearchParams]

          },

          [Symbol(options)]: {

            keepAliveTimeout: 600000,

            keepAliveMaxTimeout: 600000,

            keepAliveTimeoutThreshold: 1000,

            pipelining: 1,

            maxHeaderSize: 16384,

            headersTimeout: 30000,

            bodyTimeout: 30000,

            connect: [Function: connect],

            interceptors: undefined

          },

          [Symbol(factory)]: [Function: defaultFactory],

          [Symbol(Intercepted Dispatch)]: [Function: [dispatch]],

          [Symbol(needDrain)]: false

        },

        [Symbol(status)]: 'alive',

        [Symbol(ca fingerprint)]: null,

        [Symbol(diagnostics)]: Diagnostic {

          _events: [Object: null prototype] {},

          _eventsCount: 0,

          _maxListeners: undefined,

          [Symbol(kCapture)]: false

        },

        [Symbol(event emitter)]: EventEmitter {

          _events: [Object: null prototype] {},

          _eventsCount: 0,

          _maxListeners: undefined,

          [Symbol(kCapture)]: false

        }

      },

      attempts: 3,

      aborted: false

    },

    warnings: [Getter]

  }

}


Node.js v18.16.0

Error while initializing firebase for notifications

/app/node_modules/@elastic/transport/lib/Transport.js:528

                            : new errors_1.ConnectionError(error.message, result);

                              ^



ConnectionError: connect ECONNREFUSED 172.18.0.3:9200

    at SniffingTransport.request (/app/node_modules/@elastic/transport/lib/Transport.js:528:31)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at Client.PingApi (/app/node_modules/@elastic/elasticsearch/lib/api/api/ping.js:37:12)

    at init (/app/packages/backend/src/services/search/elasticsearch.ts:17:3) {

  meta: {

    body: undefined,

    statusCode: 0,

    headers: {},

    meta: {

      context: null,

      request: {

        params: {

          method: 'HEAD',

          path: '/',

          querystring: '',

          headers: {

            'user-agent': 'elastic-transport-js/8.3.1 (linux 5.10.47-linuxkit-x64; Node.js v18.16.0)',

            'x-elastic-client-meta': 'es=8.4.0,js=18.16.0,t=8.3.1,hc=18.16.0',

            accept: 'application/vnd.elasticsearch+json; compatible-with=8,text/plain'

          }

        },

        options: {},

        id: 1

      },

      name: 'elasticsearch-js',

      connection: Connection {

        url: <ref *1> URL {

          [Symbol(context)]: URLContext {

            href: 'http://elastic:recipesage_selfhost@elasticsearch:9200/',

            origin: 'http://elasticsearch:9200',

            protocol: 'http:',

            hostname: 'elasticsearch',

            pathname: '/',

            search: '',

            username: 'elastic',

            password: 'recipesage_selfhost',

            port: '9200',

            hash: ''

          },

          [Symbol(query)]: URLSearchParams {

            [Symbol(query)]: [],

            [Symbol(context)]: [Circular *1]

          }

        },

        tls: null,

        id: 'http://elasticsearch:9200/',

        timeout: 30000,

        headers: { authorization: 'Basic ZWxhc3RpYzpyZWNpcGVzYWdlX3NlbGZob3N0' },

        deadCount: 0,

        resurrectTimeout: 0,

        _openRequests: 0,

        weight: 1000,

        pool: <ref *2> Pool {

          _events: [Object: null prototype] {},

          _eventsCount: 0,

          _maxListeners: undefined,

          [Symbol(kCapture)]: false,

          [Symbol(destroyed)]: false,

          [Symbol(onDestroyed)]: [],

          [Symbol(closed)]: false,

          [Symbol(onClosed)]: [],

          [Symbol(queue)]: FixedQueue {

            tail: [FixedCircularBuffer],

            head: [FixedCircularBuffer]

          },

          [Symbol(clients)]: [ [Client], [Client] ],

          [Symbol(queued)]: 0,

          [Symbol(onDrain)]: [Function: onDrain],

          [Symbol(onConnect)]: [Function (anonymous)],

          [Symbol(onDisconnect)]: [Function (anonymous)],

          [Symbol(onConnectionError)]: [Function (anonymous)],

          [Symbol(stats)]: PoolStats { [Symbol(pool)]: [Circular *2] },

          [Symbol(dispatch interceptors)]: [],

          [Symbol(connections)]: 256,

          [Symbol(url)]: URL {

            [Symbol(context)]: [URLContext],

            [Symbol(query)]: [URLSearchParams]

          },

          [Symbol(options)]: {

            keepAliveTimeout: 600000,

            keepAliveMaxTimeout: 600000,

            keepAliveTimeoutThreshold: 1000,

            pipelining: 1,

            maxHeaderSize: 16384,

            headersTimeout: 30000,

            bodyTimeout: 30000,

            connect: [Function: connect],

            interceptors: undefined

          },

          [Symbol(factory)]: [Function: defaultFactory],

          [Symbol(Intercepted Dispatch)]: [Function: [dispatch]],

          [Symbol(needDrain)]: false

        },

        [Symbol(status)]: 'alive',

        [Symbol(ca fingerprint)]: null,

        [Symbol(diagnostics)]: Diagnostic {

          _events: [Object: null prototype] {},

          _eventsCount: 0,

          _maxListeners: undefined,

          [Symbol(kCapture)]: false

        },

        [Symbol(event emitter)]: EventEmitter {

          _events: [Object: null prototype] {},

          _eventsCount: 0,

          _maxListeners: undefined,

          [Symbol(kCapture)]: false

        }

      },

      attempts: 3,

      aborted: false

    },

    warnings: [Getter]

  }

}


Node.js v18.16.0

Error while initializing firebase for notifications

Search...
Stick to bottom

**Comment by julianpoy** [comment]
Odd, still seems like a problem with ElasticSearch. I assume the same logs from the ElasticSearch container?

**Comment by gavakas** [comment]
Yes, i get this error in elasticsearch logs: ERROR: Elasticsearch exited unexpectedly :(

**Comment by gavakas** [comment]
Hi Julian,

Yes it's the elasticsearch that craches based on the logs. I did a fresh install on docker, git clone your code, run docker-compose up -d and then ./migrate.sh . Then accessed by writing localhost to my browser. Again the same results. Maybe it's something else from my side but I tried in 3 different macs and got the same results. :/

**Comment by julianpoy** [comment]
This should be resolved in the latest release. Please re-clone the repo and setup again, and let me know if you still experience this issue.

ElasticSearch has been removed and replaced with Typesense, which is what RecipeSage is running in production now.

**Comment by gavakas** [comment]
Hi Julian, 

I did everything again from the beginning. Fresh docker install also. before running it for first time i did the ./migrate.sh  also. When i try to log in it says wrong password/user name although it is correct. On the other hand, the old error is gone and i was also able to create an account which was giving me the same old error before. Any idea why i can't connect with my credentials? 

Thanks

**Comment by gavakas** [comment]
I did find a workaround for anyone who might be interested. I created a new user in the selfhost enviroment and imported my recipe from my main online account. If you can fix the error mentioned on my previous post that would be awsome, if not, i trully thank you for your time and help !

**Comment by julianpoy** [comment]
Selfhost instances aren't connected to the online accounts system (or any other data), so that sounds expected. It's a completely independent instance of RecipeSage (kinda purposefully not cloud-tied).

Very glad to hear it's working. After a fair bit of debugging these last couple of months, I suspect ElasticSearch was just trying to allocate too much RAM. Typesense uses less RAM and is faster to boot.
