### ISSUE TITLE
Unable to export recipes

### ISSUE THREAD

**Issue by nick-dawson** [julianpoy/RecipeSage-selfhost#48]
Hello, I just got everything running and it works great except for exports. I'm running the default docker-compose.yml except I changed the port number. I accessed the GUI by going directly to the server IP:Port, no external access setup yet. Whenever I click on any of the export options, I get something along the lines of this:

Error: ENOENT: no such file or directory, open '/api/images/filesystem/recipeImage/2023/6/1686538455277-42017a6af810c7'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at getRecipeDataForExport (/app/packages/backend/src/routes/data.js:97:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (/app/packages/backend/src/routes/data.js:194:23)

Maybe a permissions issue on my end?

**Comment by julianpoy** [comment]
This issue should be solved by https://github.com/julianpoy/RecipeSage/commit/1438607c9efd355cc8a52b16bc7f2be7ff4aac87, but I believe that's not present in the tag currently used in the selfhost repo.

**Comment by julianpoy** [comment]
Updated in 8704ed08bd285f1c833930788ac8fe56674828e3. Please pull the latest and let me know if you still experience the issue.

**Comment by nick-dawson** [comment]
Thanks for working on it! I pulled the latest beta19, but I'm running into a new issue. This container keeps having issues: julianpoy/recipesage-selfhost:static-v2.11.0-beta19

I opened up the log and found this line that keeps repeating:

/docker-entrypoint.sh: 47: exec: tsx: not found

**Comment by julianpoy** [comment]
Thanks for debugging - I fixed the error you experienced in [f751dee](https://github.com/julianpoy/RecipeSage-selfhost/commit/f751dee52af1a0514ec2bc6fee6416c52f4bf7dc).

**Comment by nick-dawson** [comment]
I tested the fix using the current yaml and received the following error on start up:

/docker-entrypoint.sh: 47: exec: npx: not found

**Comment by julianpoy** [comment]
Is the yaml exactly the same locally as it is in GitHub? I noticed in your message above that you said:

> This container keeps having issues: julianpoy/recipesage-selfhost:static-v2.11.0-beta19 ... /docker-entrypoint.sh: 47: exec: tsx: not found

But that image is the frontend image, not the backend image and therefore doesn't run TSX. I suspect that your image tags may be mixed up between the static and api containers.

**Comment by nick-dawson** [comment]
I messed up something on my own for sure. Re-cloned and changed the port number. Bug is fixed! Thank you for creating this app and fixing this issue so quickly. I appreciate it!
