### ISSUE TITLE
Import a long txt file list of URLs (one per line)

### ISSUE THREAD

**Issue by Bit-River** [julianpoy/RecipeSage-selfhost#49]
Many thanks for RecipeSage, fantastic program and it's the only recipe manager I've tried that can parse recipes from The Guardian.

I have a list of recipes (300+) from that site in the form of a simple txt file with one URL per line, looks like this:

```
https://www.theguardian.com/lifeandstyle/2017/sep/09/apple-and-almond-tart-recipe-jeremy-lee-king-of-puddings
https://www.theguardian.com/lifeandstyle/2017/sep/01/chocolate-fridge-cake-recipe-jeremy-lee-king-of-puddings
https://www.theguardian.com/lifeandstyle/2017/sep/22/custard-tart-recipe-pastel-de-nata-jeremy-lee-quo-vadis-king-of-puddings
```

Is there a way to batch import them and I can't find it?

**Comment by julianpoy** [comment]
There's no way to batch import like this at the current time, but I'd be happy to write a script to do that.

**Comment by julianpoy** [comment]
PR for script: https://github.com/julianpoy/RecipeSage/pull/1034

Can be executed via

```
cat YOUR_URL_LIST | docker-compose exec -T backend npx tsx packages/backend/src/import-bulk.app.ts -e YOUR_ACCOUNT_EMAIL
```

**Comment by Bit-River** [comment]
Thanks a million for looking into this!

The frontend updates to beta20, but the api backend gives me:

`Error response from daemon: manifest for julianpoy/recipesage-selfhost:api-v2.11.0-beta20 not found: manifest unknown: manifest unknown`

So I haven't tried the import yet.

**Comment by julianpoy** [comment]
Looks like the CircleCI build job [failed due to a connection error](https://app.circleci.com/pipelines/github/julianpoy/RecipeSage/2274/workflows/1099a0d8-8a6a-41e0-9b2a-55368fc78d93/jobs/4318) (unrelated to RecipeSage).

The image tag is up now.

**Comment by Bit-River** [comment]
Fantastic, worked a treat!!! Thank you so much!!!

To tweak it for my setup, and in case it helps someone else - I altered the command to this:


`cat list-with-guardian.txt | docker compose --project-name recipesage-selfhost exec -T api npx tsx packages/backend/src/import-bulk.app.ts -e allrecipes@fakeemail.ie`

And here's the url file itself for completeness.

You're a superstar!!! Cheers!


[list-with-guardian.txt](https://github.com/julianpoy/RecipeSage-selfhost/files/11780148/list-with-guardian.txt)
