### ISSUE TITLE
Android App connect self-hosted server

### ISSUE THREAD

**Issue by saschamander** [julianpoy/RecipeSage-selfhost#5]
Hi,
is it possible to connect the Android app to a self-hosted server?

Didn't find anything to this topic.
Thanks in advance.

**Comment by julianpoy** [comment]
Hi @saschamander,

The Android app is just a wrapper around the PWA and offers no additional functionality over the PWA version.

Although there isn't a way to connect the Android app to the selfhosted version, you'll get the exact same functionality by following the "add to home screen" instructions on the download & install page:

.../#/install
