### ISSUE TITLE
Problems with Importing from JSON-LD file

### ISSUE THREAD

**Issue by sandy9999** [julianpoy/RecipeSage-selfhost#50]
Hi there,

I had a backup of my recipe data and after setting up RecipeSage on a new instance of mine, I tried to import from my backup JSON-LD file.

**Images are lost**. I understand this is because I uploaded images, and they are not stored as base64 but as URLs, which is reasonable. So I examined the backup volumes option.

The backup volumes that I have are:
a) elasticsearchdata.tgz
b) miniodata.tgz
c) postgresdata.tgz

The volumes that I see with the latest code and latest instance are:
a) recipesage-selfhost_apimedia
b) recipesage-selfhost_elasticsearchdata
c) recipesage-selfhost_postgresdata

I see that minio is not used anymore and that the new docker-compose.yml writes directly to file system. However, I am wondering if I can retrieve my recipe data along with the images from the backup volumes (the ones above ending with .tgz) that I have.

Thanks for your time and help!

**Comment by julianpoy** [comment]
Yep, the images should all be present in the miniodata.tgz directory. You'll want to re-add minio to your docker-compose along with it's volume definition: https://github.com/julianpoy/RecipeSage-selfhost#v200 and restore your tgz file to the minio volume.

**Comment by julianpoy** [comment]
Closing since no response, but please feel free to open up a new issue if you need additional help!
