### ISSUE TITLE
Backup automation question

### ISSUE THREAD

**Issue by nick-dawson** [julianpoy/RecipeSage-selfhost#51]
Is there a way to automate backing up the database? I would like to automate something with a cronjob, but it seems the only way is manual. This is more of a question as opposed to a feature request. If it doesn't exist, I will manually do it every so often.

**Comment by julianpoy** [comment]
I don't have any tooling to do this on the selfhosted side. All of the tooling for DB backup is pretty specific to the cloud hosted instance. That said, it shouldn't be too hard to automate locally with pgdump.

**Comment by julianpoy** [comment]
Also possible to just copy the volume to a tgz file. (https://stackoverflow.com/questions/21597463/how-to-port-data-only-volumes-from-one-host-to-another)

**Comment by nick-dawson** [comment]
Thanks! I wanted to make sure there wasn't something I was missing.
