### ISSUE TITLE
Is there a way to edit the header logo and FavIcon?

### ISSUE THREAD

**Issue by netzih** [julianpoy/RecipeSage-selfhost#52]
Right now on the top bar in place of the logo it says "RecipeSage Self Hosted", Can that be changed to my own logo?
Also, Can I add my own Favicon?

Thanks

**Comment by julianpoy** [comment]
The selfhosted version of RecipeSage isn't intended to be modified or rebranded, and carries that warning to inform users the site is an unofficial distribution since the site contains sharing and social features.
