### ISSUE TITLE
Podman support

### ISSUE THREAD

**Issue by thyeestes** [julianpoy/RecipeSage-selfhost#54]
Woud it be possible to add support for Podman pods?

Currently I think three containers are using port 3000 and two port 80, which will not work in a single pod.

**Comment by julianpoy** [comment]
Isn't podman capable of running in a full docker-compatible mode?

Is it not possible to remap ports with podman?

**Comment by julianpoy** [comment]
Correct me if I'm wrong, but each container described in the docker-compose should be represented as a separate pod within podman.

From what I can glean online, podman pods are a fairly direct parallel to kubernetes pods - in which case each of the services described in the docker-compose currently should definitely be separate pods. See the kube configs for RecipeSage production: https://github.com/julianpoy/RecipeSage/tree/master/kube

**Comment by thyeestes** [comment]
Thanks I will have a look at the kube configs.

**Comment by julianpoy** [comment]
Going to close this out for now, but please feel free to reopen if needed.
