### ISSUE TITLE
Unable to create account from welcome page

### ISSUE THREAD

**Issue by PDXUser** [julianpoy/RecipeSage-selfhost#6]
Fresh install today  of the self hosted docker image.  When I try to create my account, I get the following error:

`An unexpected error occured. Please try again.`

Is there a log file which I can look at or provide for troubleshooting?

**Comment by Typhonragewind** [comment]
You probably forgot to do this part from the setup instructions:

"You'll need Docker to run RecipeSage locally. Although you can attempt to run it without Docker, it likely won't work or will be buggy.

To start, simply start all containers: docker-compose up -d

**On first run, and when updating, you'll need to run migrations: docker-compose exec api /app/migrate**

I strongly recommend taking a backup of your volumes before migrating to avoid any potential data loss."

**Comment by PDXUser** [comment]
You are right - I had an initial issue with NGINX not wanting to run but I resolved that through a removal of the container images and reinstalling again, but I neglected the second half.  I was able to register now.  Thanks!

**Comment by julianpoy** [comment]
Sounds like this is resolved, going to close this out.
