### ISSUE TITLE
Support docker-compose.override.yml

### ISSUE THREAD

**Issue by PhilKet** [julianpoy/RecipeSage-selfhost#62]
Hey,

first of all, thanks for this awsome project! I really like it and it seems to work great.

I have a little suggestion though. It would be very useful for the selfhosted version to support a `docker-compose.override.yml` file. That would give you an easy way to change configurations in the docker-compose.yml, without directly editing it and therefore making it difficult to pull and update to a new version.

Everything needed for this to work would be a `.gitignore` with:
`docker-compose.override.yml`

**Comment by julianpoy** [comment]
I didn't realize that a docker-compose.override.yml was a thing! Happy to add that.
