### ISSUE TITLE
Cannot create user on Synology 

### ISSUE THREAD

**Issue by userforusing** [julianpoy/RecipeSage-selfhost#64]
I am trying to get recipe sage running on synology docker. I got the containers up and running but get an unexpected error creating a user. 
Here is an error I got from the recipesage-posgres log:
`2023-10-21T06:49:53.563338752Z 2023-10-21 06:49:53.562 UTC [8732] STATEMENT:  DELETE FROM "Sessions" WHERE "expires" < '2023-10-21 06:49:53.484 +00:00'
2023-10-21T07:42:52.796120170Z 2023-10-21 07:42:52.795 UTC [8892] ERROR:  relation "Users" does not exist at character 18`

I have not completed the step 3 "On first run, and when updating, you'll need to run database migrations with ./migrate.sh" because I don't know how. Does anyone know how to fix the issue or a guide that explains thr setup? My database knowledge is very limited.

**Comment by julianpoy** [comment]
Not familiar with Synology's Docker implementation. Are you unable to run the `migrate.sh` file that's included in this repository?

**Comment by userforusing** [comment]
I did try to run migrate sh. by ssh-ing into the diskstation. But it shows me:
```
./migrate.sh
Performing migrations. This could take up to 1 minute.
docker: 'compose' is not a docker command.`
```

**Comment by julianpoy** [comment]
Ah, you probably have the old `docker-compose` rather than the inbuilt `docker compose`.

Try running this command instead:

`docker-compose exec api tsx packages/backend/src/migrate`

(you'll need to do this in the directory that contains the docker-compose.yml from this repo, similar to `migrate.sh`)

**Comment by userforusing** [comment]
Yes! That did the trick. Thanks I am able to create a user and sign in know. Very excited to get started.

**Comment by julianpoy** [comment]
Glad to hear it!
