### ISSUE TITLE
RecipeSage-CLASSIFIER exited

### ISSUE THREAD

**Issue by FireFighter112WO** [julianpoy/RecipeSage-selfhost#66]
Hi,

I installed a new instance of Recipe Sage on my NAS. The installation was done via Portainer.

The RecipeSage-CLASSIFER service appears as exited. In the LOG files it says, "Platform node has already been set. Overwriting the platform with node.
Illegal instruction (core dumped)".

How can I fix this?

**Comment by TheFatPanda-Dev** [comment]
It depands on your NAS CPU and AVX suport. For some reason, this image doesn't work with CPUs that do not support AVX. I have the same problem and I own Synology DS220+ without AVX support.

**Comment by julianpoy** [comment]
Yep - see:

https://github.com/julianpoy/RecipeSage-selfhost#ingredient-instruction-classifier-container-repeatedly-crashing

It's a restriction of Tensorflow, which is maintained by Google.
