### ISSUE TITLE
Docker Hub needs a "latest"-tagged version

### ISSUE THREAD

**Issue by jeremymeyers** [julianpoy/RecipeSage-selfhost#7]
"docker pull julianpoy/recipesage-selfhost" wont work because there is no version just tagged 'latest'

**Comment by Typhonragewind** [comment]
> 
> 
> "docker pull julianpoy/recipesage-selfhost" wont work because there is no version just tagged 'latest'

The correct tags are "julianpoy/recipesage-selfhost:static-latest" and "julianpoy/recipesage-selfhost:api-latest". And you need both.

**Comment by jeremymeyers** [comment]
Not sure if you can specify that on the docker hub website but might want to mention it in the description here https://hub.docker.com/r/julianpoy/recipesage-selfhost

**Comment by Typhonragewind** [comment]
Well, it does say on the page:
>You can find instructions on how to set these images up at https://github.com/julianpoy/recipesage-selfhost

And on the github page there is a fully working docker-compose example.

**Comment by julianpoy** [comment]
Added as a note "Note: The "latest" tags are "api-latest" and "static-latest"."
