### ISSUE TITLE
Problem with label after upgrade from 2.12.12 to 2.13.2

### ISSUE THREAD

**Issue by jeremydelattre59** [julianpoy/RecipeSage-selfhost#70]
Hello,
I have been using version 2.12.12 so far without any problems.
After updating to version 2.13.2, I can no longer see recipes and I have errors showing up.
I attach the API and DB container logs
[_recipesage-db_logs.txt](https://github.com/julianpoy/RecipeSage-selfhost/files/13997958/_recipesage-db_logs.txt)
[_recipesage-api_logs.txt](https://github.com/julianpoy/RecipeSage-selfhost/files/13997959/_recipesage-api_logs.txt)

Regards,
Jeremy

**Comment by julianpoy** [comment]
Hi Jeremy,

Just to confirm, this is after running the required migration steps?

**Comment by julianpoy** [comment]
Referring to the notes posted both here: https://github.com/julianpoy/RecipeSage-selfhost/releases/tag/v4.0.0 and here: https://github.com/julianpoy/RecipeSage-selfhost#changelog

If so, would you be able to post the exact steps you went through as part of upgrading to the new version?

**Comment by jeremydelattre59** [comment]
Hi,
I restart from my backup of 2.12.12 database and app. All is OK in the app
After upgrading to 2.13.2, I launch the 2 command lines :
![image](https://github.com/julianpoy/RecipeSage-selfhost/assets/66867404/2491c263-f6bd-4523-a729-b6abb1074508)

But I have always the problem : 
![image](https://github.com/julianpoy/RecipeSage-selfhost/assets/66867404/82e40c87-5844-4cb1-9834-23efd6dde407)

And when I click on the 3rd recipe : 
![image](https://github.com/julianpoy/RecipeSage-selfhost/assets/66867404/792a1714-370f-49b8-80b8-75f7fe9f026c)

When I relaunch the 2 command lines :
![image](https://github.com/julianpoy/RecipeSage-selfhost/assets/66867404/6c3d4b82-ae7a-4f99-890e-f120a9a38ad0)

**Comment by jeremydelattre59** [comment]
I just tried to start from scratch (version 2.13.2 and new database). I launch the 2 command lines.
![image](https://github.com/julianpoy/RecipeSage-selfhost/assets/66867404/8ac1eecf-02b4-4c22-a76c-f2de68d46f75)
![image](https://github.com/julianpoy/RecipeSage-selfhost/assets/66867404/a0557975-d7f8-48c5-abf3-c4f432fcc38f)
![image](https://github.com/julianpoy/RecipeSage-selfhost/assets/66867404/388a9a7f-4f58-4106-818e-1ff1f406e362)
![image](https://github.com/julianpoy/RecipeSage-selfhost/assets/66867404/a9dc13bd-4fca-4a03-9d4e-310c8af34866)
![image](https://github.com/julianpoy/RecipeSage-selfhost/assets/66867404/45a05b59-5ca3-4ff5-aded-6406ce03d6a4)
![image](https://github.com/julianpoy/RecipeSage-selfhost/assets/66867404/5f2076dd-d2c5-44c6-ab17-55813db06545)
![image](https://github.com/julianpoy/RecipeSage-selfhost/assets/66867404/312e7e5f-7e57-4d8e-abed-d98f1ea4d8f9)


Same error :
![image](https://github.com/julianpoy/RecipeSage-selfhost/assets/66867404/b182dd11-69d6-4156-875d-d1beffbf855b)

And log : 
[_recipesage-api_logs_new.txt](https://github.com/julianpoy/RecipeSage-selfhost/files/13999121/_recipesage-api_logs_new.txt)

**Comment by julianpoy** [comment]
Can you confirm that you updated to the latest version of the docker-compose included in this repository? If you have customized it in any way please attach your docker-compose.yaml

**Comment by jeremydelattre59** [comment]
Indeed, the problem comes from docker-compose.yaml. Using the one made available by just adapting the version to put 2.13.2 and defines my network, everything works.
So I'm going to start from this one to put back my personalization and the healthchecks.
My apologies for the inconvenience

**Comment by julianpoy** [comment]
No worries! Glad to hear it.

I did just update the notes to include a 4th step (restart), since I did note that was necessary during the upgrade process, so thanks regardless!
