### ISSUE TITLE
docker compose for synology - small errors

### ISSUE THREAD

**Issue by skar-cgn** [julianpoy/RecipeSage-selfhost#71]
Hi, 
I found two small issues in the instruction for installing this nice software on a synology nas. 
1) In den docker-compose.yml there are two character missing: 
IS: postgresdata:/var/lib/postgresql/data
SHOULD: **-** postgresdata:/var/lib/postgresql/data
IS: typesensedata:/data
SHOULD: **-** typesensedata:/data
2) In the SETUP-SYNOLOGY.md the images in step 2 and 3 are the same. I would assume the image in step 3 should be "synology-new-project.png"

My Git skills are just not existing, so I can not create a MR. Sorry for that. Thanks for this nice software.

Regards
Skar

**Comment by julianpoy** [comment]
Thanks for the issue!

I've fixed the first in https://github.com/julianpoy/RecipeSage-selfhost/commit/a657459a09447685c2146922455cf63126933bce

I've fixed the second in https://github.com/julianpoy/RecipeSage-selfhost/commit/cdca16f2420877eabc7165a265f5eec295990290
