### ISSUE TITLE
Broken image when I print recipe

### ISSUE THREAD

**Issue by jeremydelattre59** [julianpoy/RecipeSage-selfhost#73]
**Describe the issue**
Hello,
Image in my Recipe is OK but when I want to print my recipe, image is broken.
![image](https://github.com/julianpoy/RecipeSage-selfhost/assets/66867404/95ddf94b-1588-4f2d-9e61-6ad7f369e013)

![image](https://github.com/julianpoy/RecipeSage-selfhost/assets/66867404/4507cc14-71e4-48bc-8288-3903253a3f6c)

![image](https://github.com/julianpoy/RecipeSage-selfhost/assets/66867404/ed778c6a-8c2d-46e2-b30a-632869053cfb)

Image URL for recipe : http://recette.homelinux.maison/api/images/filesystem/recipeImage/2024/1/1705792789763-0cbc546b1acef6

Image URL for print  : http://recette.homelinux.maison/api/print/api/images/filesystem/recipeImage/2024/1/1705792789763-0cbc546b1acef6
There is also **/api/print** in the url for print

I don't know is the problem is only for selfhost repo or the main tracker for RecipeSage

Regards,
Jeremy

**Please do the following and check the boxes before filing**
[ ] I have attached my docker-compose.yaml to the issue
[ ] I have attached the logs for my `api` container to the issue
[ ] My issue is related to this selfhost repo, not the main tracker for RecipeSage [here](https://github.com/julianpoy/RecipeSage/issues)

**Comment by julianpoy** [comment]
Thanks for the bug report! I'll look into this as soon as I can.

**Comment by julianpoy** [comment]
Taking a look into this, apologies for the long delay.
