### ISSUE TITLE
activate.sh script needs a second argument

### ISSUE THREAD

**Issue by elChapoSing** [julianpoy/RecipeSage-selfhost#74]
**Describe the issue**

When running the script to activate (after contributing of course :) ), it fails.

> npx ts-node --swc --project packages/backend/tsconfig.json packages/backend/src/activate themail@email.com

needs to be 

> npx ts-node --swc --project packages/backend/tsconfig.json packages/backend/src/activate themail@email.com Forever

Think the default is 'forever' which does not match what is expected in the subscription models.

**Please do the following and check the boxes before filing**
[ ] I have attached my docker-compose.yaml to the issue
[ ] I have attached the logs for my `api` container to the issue
[X ] My issue is related to this selfhost repo, not the main tracker for RecipeSage [here](https://github.com/julianpoy/RecipeSage/issues)

**Comment by julianpoy** [comment]
Indeed a bug! It should be lowercase "forever" as the default and "Forever" should not work.

**Comment by julianpoy** [comment]
Fixed in the latest version.
