### ISSUE TITLE
reset user password

### ISSUE THREAD

**Issue by Loxatan** [julianpoy/RecipeSage-selfhost#75]
Hi Julian, 
i hope you doing well.

Is there a chance to change the password form a user with the command line?
I set it up a long time ago and it was running until now. Now i need to enter the user login but i have no clue at all.
I tried to reset it with option "forget password" but i wont work. I mean for sure, i dindnt set up a mail server for this.

**Please do the following and check the boxes before filing**
[X] I have attached my docker-compose.yaml to the issue
[X] I have attached the logs for my `api` container to the issue
[X] My issue is related to this selfhost repo, not the main tracker for RecipeSage [here](https://github.com/julianpoy/RecipeSage/issues)

[config_apilog.zip](https://github.com/julianpoy/RecipeSage-selfhost/files/15321334/config_apilog.zip)

**Comment by julianpoy** [comment]
Without direct database access or a mail server - there is no way.

If you exec into the DB container and open a SQL command line, you could query against the users table, find the user ID for your user, then add an entry in the sessions table.

**Comment by julianpoy** [comment]
Going to close out, but please feel free to let me know if you have any further issues here.
