### ISSUE TITLE
Unable to create account

### ISSUE THREAD

**Issue by allegiancetech** [julianpoy/RecipeSage-selfhost#76]
**Describe the issue**
Installed using compose file, received error of "unexpected error occurred" when creating account.  I saw other entries where you suggest pulling latest versions.  I did that, and now I'm getting the same error, but it works longer before throwing up the error, and the error is in a pop-up now vs a banner as originally.  My api container log is empty, but am attaching

**Please do the following and check the boxes before filing**
[ X] I have attached my docker-compose.yaml to the issue
[ X] I have attached the logs for my `api` container to the issue
[X
[Archive 3.zip](https://github.com/julianpoy/RecipeSage-selfhost/files/15358916/Archive.3.zip)
 ] My issue is related to this selfhost repo, not the main tracker for RecipeSage [here](https://github.com/julianpoy/RecipeSage/issues)

**Comment by allegiancetech** [comment]
So, the first time I updated the individual containers to the latest and that did not seem to work.  I updated the compose file this time referencing the latest container versions in it, and re-deployed.  That seemed to work.  Thank you!

**Comment by julianpoy** [comment]
Hi there! "Unexpected error occurred" is almost always DB migrations not having been run. Your latest comment makes it sound like everything is resolved, though.

**Comment by julianpoy** [comment]
If possible, yes! Would need the logs attached and everything.
