### ISSUE TITLE
An Unexpected Error Occurred pop-up when navigating

### ISSUE THREAD

**Issue by DoubleJCream** [julianpoy/RecipeSage-selfhost#81]
**Describe the issue**
I installed the docker version based on Marius's install of RecipeSage;
[https://mariushosting.com/how-to-install-recipesage-on-your-synology-nas/](url)
followed it almost to the letter - the exact docker compose file - the same same proxy.config file - and the same command to migrate the db - 'tsx packages/backend/src/migrate'.
The only difference i can see is that i am reverse proxing off the synology from port 6915 instead of the 443 port he uses. However the issue occurs whether i take the SSL port or the regular http directly to the Synology IP http://SynologyIP:6914
The containers all are created and seem to be working - when i do the initial login i get the create account webpage, which seems to work fine until i get to the default page of 'My Recipes, at which point i get the pop-up with the message;
An Unexpected Error Occurred. Please check your server logs as well as the self hosting FAQ.
If i go to 'Manage Labels' i get the same error, 'Recipe Inbox' as well, 'Cooking Assistant', the only place where i don't see to see this error is in 'Shopping Lists'

**Please do the following and check the boxes before filing**
[ x] I have attached my docker-compose.yaml to the issue

`version: "3.9"
services:
  db:
    image: postgres:16
    container_name: RecipeSage-DB
    hostname: recipesage-db
    mem_limit: 1024m
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "recipesage", "-U", "recipesageuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /volume1/docker/recipesage/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: recipesage
      POSTGRES_USER: recipesageuser
      POSTGRES_PASSWORD: recipesagepass
    restart: on-failure:5

  pushpin:
    image: julianpoy/pushpin:2023-09-17
    container_name: RecipeSage-PUSHPIN
    hostname: pushpin
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    environment:
      target: api:3000
    restart: on-failure:5

  typesense:
    image: typesense/typesense:0.25.1
    command: "--data-dir /data --api-key=recipesage_selfhost --enable-cors"
    container_name: RecipeSage-TYPESENSE
    hostname: typesense
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    read_only: true
    user: 1026:100
    volumes:
      - /volume1/docker/recipesage/typesense:/data:rw
    restart: on-failure:5

  browserless:
    image: browserless/chrome:1.61-puppeteer-21.4.1
    container_name: RecipeSage-BROWSER
    hostname: browserless
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    user: 1026:100
    environment:
      MAX_CONCURRENT_SESSIONS: 3
      MAX_QUEUE_LENGTH: 10
    restart: on-failure:5

  ingredient-instruction-classifier:
    image: julianpoy/ingredient-instruction-classifier:1.4.9
    container_name: RecipeSage-CLASSIFIER
    hostname: ingredient-instruction-classifier
    mem_limit: 2g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    read_only: true
    user: 1026:100
    environment:
      SENTENCE_EMBEDDING_BATCH_SIZE: 200
      PREDICTION_CONCURRENCY: 4
    restart: on-failure:5

  api:
    image: julianpoy/recipesage-selfhost:api-latest
    command: npx ts-node --swc --project packages/backend/tsconfig.json packages/backend/src/bin/www
    container_name: RecipeSage-API
    hostname: api
    mem_limit: 2g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    volumes:
      - /volume1/docker/recipesage/apimedia:/rs-media:rw
    environment:
      STORAGE_TYPE: filesystem
      FILESYSTEM_STORAGE_PATH: /rs-media
      NODE_ENV: selfhost
      VERBOSE: false
      VERSION: selfhost
      POSTGRES_DB: recipesage
      POSTGRES_USER: recipesageuser
      POSTGRES_PASSWORD: recipesagepass
      POSTGRES_PORT: 5432
      POSTGRES_HOST: recipesage-db
      POSTGRES_SSL: false
      POSTGRES_LOGGING: false
      DATABASE_URL: postgresql://recipesageuser:recipesagepass@recipesage-db:5432/recipesage
      GCM_KEYPAIR: 
      SENTRY_DSN: 
      GRIP_URL: http://pushpin:5561/
      GRIP_KEY: changeme
      SEARCH_PROVIDER: typesense
      TYPESENSE_NODES: '[{"host": "typesense", "port": 8108, "protocol": "http"}]'
      TYPESENSE_API_KEY: recipesage_selfhost
      STRIPE_SK: 
      STRIPE_WEBHOOK_SECRET: 
      BROWSERLESS_HOST: browserless
      BROWSERLESS_PORT: 3000
      INGREDIENT_INSTRUCTION_CLASSIFIER_URL: http://ingredient-instruction-classifier:3000/
    restart: on-failure:5
    depends_on:
      db:
        condition: service_healthy
      pushpin:
        condition: service_started
      typesense:
        condition: service_started
      browserless:
        condition: service_started

  static:
    image: julianpoy/recipesage-selfhost:static-latest
    container_name: RecipeSage-STATIC
    hostname: static
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    environment:
      API_BASE_OVERRIDE: null
    restart: on-failure:5

  proxy:
    image: nginx:latest
    container_name: RecipeSage-PROXY
    hostname: proxy
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    ports:
      - 6914:80
    volumes:
      - /volume1/docker/recipesage/proxy.conf:/etc/nginx/conf.d/default.conf:ro
    restart: on-failure:5
    depends_on:
      static:
        condition: service_started
      api:
        condition: service_started
      pushpin:
        condition: service_started`

[x ] I have attached the logs for my `api` container to the issue

`    at async resolve (/app/node_modules/@trpc/server/dist/index.js:483:24)
    at async inputToProcedureCall (/app/node_modules/@trpc/server/dist/resolveHTTPResponse-b7a8a1c9.js:48:22)
GET /trpc/mealPlans.getMealPlanItems?input=%7B%22json%22%3A%7B%22mealPlanId%22%3A%223401bc65-747e-40a9-b014-81a375927de1%22%7D%7D 500 12.671 ms - -
GET /trpc/users.getMe?input=%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D 200 6.731 ms - -
GET /trpc/mealPlans.getMealPlans?input=%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D 200 9.060 ms - -
GET /shoppingLists?token=828a90320c4219b3b144217c2e2be41c9d263131f7ce569667e5241e3e5dd8c5899ffc42672e9f371c82e0a17dc3d87a& 304 10.439 ms - -
GET /messages/threads?token=828a90320c4219b3b144217c2e2be41c9d263131f7ce569667e5241e3e5dd8c5899ffc42672e9f371c82e0a17dc3d87a& 304 6.864 ms - -
POST /shoppingLists?token=828a90320c4219b3b144217c2e2be41c9d263131f7ce569667e5241e3e5dd8c5899ffc42672e9f371c82e0a17dc3d87a& 200 98.404 ms - 188
GET /shoppingLists/89b0eef9-edfb-452f-9644-841d433e7901?token=828a90320c4219b3b144217c2e2be41c9d263131f7ce569667e5241e3e5dd8c5899ffc42672e9f371c82e0a17dc3d87a& 200 12.556 ms - 330
POST /shoppingLists/89b0eef9-edfb-452f-9644-841d433e7901?token=828a90320c4219b3b144217c2e2be41c9d263131f7ce569667e5241e3e5dd8c5899ffc42672e9f371c82e0a17dc3d87a& 200 92.106 ms - 27
GET /shoppingLists/89b0eef9-edfb-452f-9644-841d433e7901?token=828a90320c4219b3b144217c2e2be41c9d263131f7ce569667e5241e3e5dd8c5899ffc42672e9f371c82e0a17dc3d87a& 200 17.562 ms - 692
POST /shoppingLists/89b0eef9-edfb-452f-9644-841d433e7901?token=828a90320c4219b3b144217c2e2be41c9d263131f7ce569667e5241e3e5dd8c5899ffc42672e9f371c82e0a17dc3d87a& 200 75.812 ms - 27
GET /shoppingLists/89b0eef9-edfb-452f-9644-841d433e7901?token=828a90320c4219b3b144217c2e2be41c9d263131f7ce569667e5241e3e5dd8c5899ffc42672e9f371c82e0a17dc3d87a& 200 25.156 ms - 2170
GET /shoppingLists?token=828a90320c4219b3b144217c2e2be41c9d263131f7ce569667e5241e3e5dd8c5899ffc42672e9f371c82e0a17dc3d87a& 200 10.304 ms - 679
GET /shoppingLists/59088434-abb1-4d02-b6f1-d7ee2989d43e?token=828a90320c4219b3b144217c2e2be41c9d263131f7ce569667e5241e3e5dd8c5899ffc42672e9f371c82e0a17dc3d87a& 304 26.602 ms - -
GET /shoppingLists?token=828a90320c4219b3b144217c2e2be41c9d263131f7ce569667e5241e3e5dd8c5899ffc42672e9f371c82e0a17dc3d87a& 304 9.429 ms - -
GET /messages/threads?token=828a90320c4219b3b144217c2e2be41c9d263131f7ce569667e5241e3e5dd8c5899ffc42672e9f371c82e0a17dc3d87a& 304 7.686 ms - -
GET /users/by-email?token=828a90320c4219b3b144217c2e2be41c9d263131f7ce569667e5241e3e5dd8c5899ffc42672e9f371c82e0a17dc3d87a&email=asdasda 404 2.434 ms - 570
Error: No user with that email!
    at constructError (/app/packages/backend/src/utils/errors.js:2:13)
    at NotFound (/app/packages/backend/src/utils/errors.js:10:38)
    at /app/packages/backend/src/routes/users.js:563:21
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/packages/backend/src/utils/wrapRequestWithErrorHandler.js:4:7
POST /shoppingLists?token=828a90320c4219b3b144217c2e2be41c9d263131f7ce569667e5241e3e5dd8c5899ffc42672e9f371c82e0a17dc3d87a& 200 45.919 ms - 188
GET /shoppingLists/2fdd63bc-d7af-4469-8abb-70e0a27b0c62?token=828a90320c4219b3b144217c2e2be41c9d263131f7ce569667e5241e3e5dd8c5899ffc42672e9f371c82e0a17dc3d87a& 200 16.279 ms - 330
POST /shoppingLists/2fdd63bc-d7af-4469-8abb-70e0a27b0c62?token=828a90320c4219b3b144217c2e2be41c9d263131f7ce569667e5241e3e5dd8c5899ffc42672e9f371c82e0a17dc3d87a& 200 87.954 ms - 27
GET /shoppingLists/2fdd63bc-d7af-4469-8abb-70e0a27b0c62?token=828a90320c4219b3b144217c2e2be41c9d263131f7ce569667e5241e3e5dd8c5899ffc42672e9f371c82e0a17dc3d87a& 200 16.941 ms - 724
GET /shoppingLists?token=828a90320c4219b3b144217c2e2be41c9d263131f7ce569667e5241e3e5dd8c5899ffc42672e9f371c82e0a17dc3d87a& 200 10.117 ms - 1017
GET /shoppingLists/2fdd63bc-d7af-4469-8abb-70e0a27b0c62?token=828a90320c4219b3b144217c2e2be41c9d263131f7ce569667e5241e3e5dd8c5899ffc42672e9f371c82e0a17dc3d87a& 304 13.904 ms - -
GET /shoppingLists?token=828a90320c4219b3b144217c2e2be41c9d263131f7ce569667e5241e3e5dd8c5899ffc42672e9f371c82e0a17dc3d87a& 304 9.678 ms - -
prisma:error 
Invalid `prisma.label.findMany()` invocation in
/app/packages/trpc/src/procedures/labels/getLabels.ts:10:37
   7 const session = ctx.session;
   8 validateTrpcSession(session);
PrismaClientKnownRequestError: 
Invalid `prisma.label.findMany()` invocation in
/app/packages/trpc/src/procedures/labels/getLabels.ts:10:37
   7 const session = ctx.session;
   8 validateTrpcSession(session);
   9 
→ 10 const labels = await prisma.label.findMany(
The column `Labels.labelGroupId` does not exist in the current database.
    at Mn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7753)
    ... 8 lines matching cause stack trace ...
    at async Promise.all (index 0) {
  code: 'INTERNAL_SERVER_ERROR',
  name: 'TRPCError',
  [cause]: PrismaClientKnownRequestError: 
  Invalid `prisma.label.findMany()` invocation in
  /app/packages/trpc/src/procedures/labels/getLabels.ts:10:37
  
     7 const session = ctx.session;
     8 validateTrpcSession(session);
     9 
  → 10 const labels = await prisma.label.findMany(
  The column `Labels.labelGroupId` does not exist in the current database.
      at Mn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7753)
   9 
→ 10 const labels = await prisma.label.findMany(
The column `Labels.labelGroupId` does not exist in the current database.
      at Mn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7061)
      at Mn.request (/app/node_modules/@prisma/client/runtime/library.js:121:6745)
      at async l (/app/node_modules/@prisma/client/runtime/library.js:130:9633)
      at async /app/packages/trpc/src/procedures/labels/getLabels.ts:10:18
      at async resolveMiddleware (/app/node_modules/@trpc/server/dist/index.js:423:30)
      at async callRecursive (/app/node_modules/@trpc/server/dist/index.js:453:32)
      at async resolve (/app/node_modules/@trpc/server/dist/index.js:483:24)
      at async inputToProcedureCall (/app/node_modules/@trpc/server/dist/resolveHTTPResponse-b7a8a1c9.js:48:22)
      at async Promise.all (index 0) {
    code: 'P2022',
    clientVersion: '5.20.0',
    meta: { modelName: 'Label', column: 'Labels.labelGroupId' }
  }
} PrismaClientKnownRequestError: 
Invalid `prisma.label.findMany()` invocation in
/app/packages/trpc/src/procedures/labels/getLabels.ts:10:37
   7 const session = ctx.session;
   8 validateTrpcSession(session);
   9 
→ 10 const labels = await prisma.label.findMany(
The column `Labels.labelGroupId` does not exist in the current database.
    at Mn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7753)
    at Mn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7061)
    at Mn.request (/app/node_modules/@prisma/client/runtime/library.js:121:6745)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:130:9633)
    at async /app/packages/trpc/src/procedures/labels/getLabels.ts:10:18
    at async resolveMiddleware (/app/node_modules/@trpc/server/dist/index.js:423:30)
    at async callRecursive (/app/node_modules/@trpc/server/dist/index.js:453:32)
    at async resolve (/app/node_modules/@trpc/server/dist/index.js:483:24)
    at async inputToProcedureCall (/app/node_modules/@trpc/server/dist/resolveHTTPResponse-b7a8a1c9.js:48:22)
    at async Promise.all (index 0)
GET /trpc/labels.getLabels?input=%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D 500 10.826 ms - -
GET /trpc/recipes.getRecipes?input=%7B%22json%22%3A%7B%22folder%22%3A%22main%22%2C%22orderBy%22%3A%22title%22%2C%22orderDirection%22%3A%22asc%22%2C%22offset%22%3A0%2C%22limit%22%3A50%2C%22labels%22%3Anull%2C%22labelIntersection%22%3Afalse%2C%22includeAllFriends%22%3Afalse%2C%22ratings%22%3Anull%2C%22userIds%22%3Anull%7D%2C%22meta%22%3A%7B%22values%22%3A%7B%22labels%22%3A%5B%22undefined%22%5D%2C%22ratings%22%3A%5B%22undefined%22%5D%2C%22userIds%22%3A%5B%22undefined%22%5D%7D%7D%7D 200 20.617 ms - -
GET /users/profile?token=828a90320c4219b3b144217c2e2be41c9d263131f7ce569667e5241e3e5dd8c5899ffc42672e9f371c82e0a17dc3d87a& 304 51.867 ms - -
GET /users/friends?token=828a90320c4219b3b144217c2e2be41c9d263131f7ce569667e5241e3e5dd8c5899ffc42672e9f371c82e0a17dc3d87a& 304 46.102 ms - -
`

[ x] My issue is related to this selfhost repo, not the main tracker for RecipeSage [here](https://github.com/julianpoy/RecipeSage/issues)

also the proxyfile is;
`server {
  client_max_body_size 1G;

	listen 80;

	server_name localhost;

  location /grip/ws {

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_connect_timeout 1h;
    proxy_send_timeout 1h;
    proxy_read_timeout 1h;
    proxy_pass http://pushpin:7999/ws;
  }

  # Alias minio in case minio container is not present
  set $minio http://minio:9000;
  location /minio/ {
    rewrite ^/minio/(.*)$ /$1 break;
    proxy_pass $minio;
  }

  location /api/ {
    proxy_pass http://api:3000/;
  }

	location / {
    proxy_pass http://static:80/;
	}
}`

Let me know if i can provide something else - it would be great to get this working properly
thanks

**Comment by julianpoy** [comment]
Unsure who Marius is, but he's charging money for a proxy.conf file that he doesn't have a license to. Aggravating to say the least.

His guide is definitely not officially endorsed, and seems to be written for a very old version of RecipeSage (even though it claims up top to be for the latest version).

There's a guide within this repo for how to host on Synology, and can be found via the README.

Going to close this issue out, but feel free to open another if you run into issues following the official guide. I recommend deleting all containers/resources created by following the guide on that blog before starting the official install steps.
